const ACADEMY_DATA_FULL = [
  { year: "2025", chineseTitle: "罪人", englishTitle: "Sinners", cinematographer: "Autumn Durald Arkapaw", award: "Winner" , koreanTitle: "시너스" },
  { year: "2025", chineseTitle: "弗兰肯斯坦", englishTitle: "Frankenstein", cinematographer: "Dan Laustsen", award: "Nominee" , koreanTitle: "프랑켄슈타인" },
  { year: "2025", chineseTitle: "至尊马蒂", englishTitle: "Marty Supreme", cinematographer: "Darius Khondji", award: "Nominee" , koreanTitle: "마티 슈프림" },
  { year: "2025", chineseTitle: "一战再战", englishTitle: "One Battle After Another", cinematographer: "Michael Bauman", award: "Nominee" , koreanTitle: "원 배틀 애프터 어나더" },
  { year: "2025", chineseTitle: "火车梦", englishTitle: "Train Dreams", cinematographer: "Adolpho Veloso", award: "Nominee" , koreanTitle: "트레인 드림스" },
  { year: "2024", chineseTitle: "粗野派", englishTitle: "The Brutalist", cinematographer: "Lol Crawley", award: "Winner" , koreanTitle: "브루탈리스트" },
  { year: "2024", chineseTitle: "沙丘2", englishTitle: "Dune: Part Two", cinematographer: "Greig Fraser", award: "Nominee" , koreanTitle: "듄: 파트 2" },
  { year: "2024", chineseTitle: "艾米莉亚·佩雷斯", englishTitle: "Emilia Pérez", cinematographer: "Paul Guilhaume", award: "Nominee" , koreanTitle: "에밀리아 페레즈" },
  { year: "2024", chineseTitle: "玛丽亚", englishTitle: "Maria", cinematographer: "Ed Lachman", award: "Nominee" , koreanTitle: "마리아" },
  { year: "2024", chineseTitle: "诺斯费拉图", englishTitle: "Nosferatu", cinematographer: "Jarin Blaschke", award: "Nominee" , koreanTitle: "노스페라투" },
  { year: "2023", chineseTitle: "伯爵", englishTitle: "El Conde", cinematographer: "Edward Lachman", award: "Nominee" , koreanTitle: "엘 콘데" },
  { year: "2023", chineseTitle: "花月杀手", englishTitle: "Killers of the Flower Moon", cinematographer: "Rodrigo Prieto", award: "Nominee" , koreanTitle: "플라워 킬링 문" },
  { year: "2023", chineseTitle: "音乐大师", englishTitle: "Maestro", cinematographer: "Matthew Libatique", award: "Nominee" , koreanTitle: "마에스트로" },
  { year: "2023", chineseTitle: "奥本海默", englishTitle: "Oppenheimer", cinematographer: "Hoyte van Hoytema", award: "Winner" , koreanTitle: "오펜하이머" },
  { year: "2023", chineseTitle: "可怜的东西", englishTitle: "Poor Things", cinematographer: "Robbie Ryan", award: "Nominee" , koreanTitle: "포어 티징스" },
  { year: "2022", chineseTitle: "西线无战事", englishTitle: "All Quiet on the Western Front", cinematographer: "James Friend", award: "Winner" , koreanTitle: "서부 전선 이상 없다" },
  { year: "2022", chineseTitle: "诗人", englishTitle: "Bardo, False Chronicle of a Handful of Truths", cinematographer: "Darius Khondji", award: "Nominee" , koreanTitle: "바르도" },
  { year: "2022", chineseTitle: "猫王", englishTitle: "Elvis", cinematographer: "Mandy Walker", award: "Nominee" , koreanTitle: "엘비스" },
  { year: "2022", chineseTitle: "光之帝国", englishTitle: "Empire of Light", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "빛의 제국" },
  { year: "2022", chineseTitle: "塔尔", englishTitle: "Tár", cinematographer: "Florian Hoffmeister", award: "Nominee" , koreanTitle: "타르" },
  { year: "2021", chineseTitle: "沙丘", englishTitle: "Dune", cinematographer: "Greig Fraser", award: "Winner" , koreanTitle: "듄" },
  { year: "2021", chineseTitle: "噩梦大道", englishTitle: "Nightmare Alley", cinematographer: "Dan Laustsen", award: "Nominee" , koreanTitle: "나이트메어 앨리" },
  { year: "2021", chineseTitle: "犬之力", englishTitle: "The Power of the Dog", cinematographer: "Ari Wegner", award: "Nominee" , koreanTitle: "파워 오브 더 독" },
  { year: "2021", chineseTitle: "麦克白的悲剧", englishTitle: "The Tragedy of Macbeth", cinematographer: "Bruno Delbonnel", award: "Nominee" , koreanTitle: "맥베스의 비극" },
  { year: "2021", chineseTitle: "西区故事", englishTitle: "West Side Story", cinematographer: "Janusz Kamiński", award: "Nominee" , koreanTitle: "웨스트 사이드 스토리" },
  { year: "2020", chineseTitle: "曼克", englishTitle: "Mank", cinematographer: "Erik Messerschmidt", award: "Winner" , koreanTitle: "맹크" },
  { year: "2020", chineseTitle: "犹大与黑色救世者", englishTitle: "Judas and the Black Messiah", cinematographer: "Sean Bobbitt", award: "Nominee" , koreanTitle: "유다와 블랙 메시아" },
  { year: "2020", chineseTitle: "世界新闻", englishTitle: "News of the World", cinematographer: "Dariusz Wolski", award: "Nominee" , koreanTitle: "뉴스 오브 더 월드" },
  { year: "2020", chineseTitle: "游牧之地", englishTitle: "Nomadland", cinematographer: "Joshua James Richards", award: "Nominee" , koreanTitle: "노매드랜드" },
  { year: "2020", chineseTitle: "芝加哥七人组的审判", englishTitle: "The Trial of the Chicago 7", cinematographer: "Phedon Papamichael", award: "Nominee" , koreanTitle: "시카고 7인 재판" },
  { year: "2019", chineseTitle: "一九一七", englishTitle: "1917", cinematographer: "Roger Deakins", award: "Winner" , koreanTitle: "1917" },
  { year: "2019", chineseTitle: "爱尔兰人", englishTitle: "The Irishman", cinematographer: "Rodrigo Prieto", award: "Nominee" , koreanTitle: "아이리시맨" },
  { year: "2019", chineseTitle: "小丑", englishTitle: "Joker", cinematographer: "Lawrence Sher", award: "Nominee" , koreanTitle: "조커" },
  { year: "2019", chineseTitle: "灯塔", englishTitle: "The Lighthouse", cinematographer: "Jarin Blaschke", award: "Nominee" , koreanTitle: "라이트하우스" },
  { year: "2019", chineseTitle: "好莱坞往事", englishTitle: "Once Upon a Time in Hollywood", cinematographer: "Robert Richardson", award: "Nominee" , koreanTitle: "원스 어폰 어 타임 인 할리우드" },
  { year: "2018", chineseTitle: "罗马", englishTitle: "Roma", cinematographer: "Alfonso Cuarón", award: "Winner" , koreanTitle: "로마" },
  { year: "2018", chineseTitle: "冷战", englishTitle: "Cold War", cinematographer: "Łukasz Żal", award: "Nominee" , koreanTitle: "콜드 워" },
  { year: "2018", chineseTitle: "宠儿", englishTitle: "The Favourite", cinematographer: "Robbie Ryan", award: "Nominee" , koreanTitle: "더 페이버릿" },
  { year: "2018", chineseTitle: "永不瞑目", englishTitle: "Never Look Away", cinematographer: "Caleb Deschanel", award: "Nominee" , koreanTitle: "네버 룩 어웨이" },
  { year: "2018", chineseTitle: "一个明星的诞生", englishTitle: "A Star Is Born", cinematographer: "Matthew Libatique", award: "Nominee" , koreanTitle: "스타 이즈 본" },
  { year: "2017", chineseTitle: "银翼杀手2049", englishTitle: "Blade Runner 2049", cinematographer: "Roger Deakins", award: "Winner" , koreanTitle: "블레이드 러너 2049" },
  { year: "2017", chineseTitle: "黑暗时刻", englishTitle: "Darkest Hour", cinematographer: "Bruno Delbonnel", award: "Nominee" , koreanTitle: "다키스트 아워" },
  { year: "2017", chineseTitle: "敦刻尔克", englishTitle: "Dunkirk", cinematographer: "Hoyte van Hoytema", award: "Nominee" , koreanTitle: "덩케르크" },
  { year: "2017", chineseTitle: "泥土之界", englishTitle: "Mudbound", cinematographer: "Rachel Morrison", award: "Nominee" , koreanTitle: "머드바운드" },
  { year: "2017", chineseTitle: "水形物语", englishTitle: "The Shape of Water", cinematographer: "Dan Laustsen", award: "Nominee" , koreanTitle: "셰이프 오브 워터" },
  { year: "2016", chineseTitle: "爱乐之城", englishTitle: "La La Land", cinematographer: "Linus Sandgren", award: "Winner" , koreanTitle: "라라랜드" },
  { year: "2016", chineseTitle: "到来", englishTitle: "Arrival", cinematographer: "Bradford Young", award: "Nominee" , koreanTitle: "컨택트" },
  { year: "2016", chineseTitle: "狮子", englishTitle: "Lion", cinematographer: "Greig Fraser", award: "Nominee" , koreanTitle: "라이언" },
  { year: "2016", chineseTitle: "月光男孩", englishTitle: "Moonlight", cinematographer: "James Laxton", award: "Nominee" , koreanTitle: "문라이트" },
  { year: "2016", chineseTitle: "寂静", englishTitle: "Silence", cinematographer: "Rodrigo Prieto", award: "Nominee" , koreanTitle: "" },
  { year: "2015", chineseTitle: "荒野猎人", englishTitle: "The Revenant", cinematographer: "Emmanuel Lubezki", award: "Winner" , koreanTitle: "레버넌트" },
  { year: "2015", chineseTitle: "卡罗尔", englishTitle: "Carol", cinematographer: "Edward Lachman", award: "Nominee" , koreanTitle: "" },
  { year: "2015", chineseTitle: "八恶人", englishTitle: "The Hateful Eight", cinematographer: "Robert Richardson", award: "Nominee" , koreanTitle: "헤이트풀 에이트" },
  { year: "2015", chineseTitle: "疯狂的麦克斯：狂暴之路", englishTitle: "Mad Max: Fury Road", cinematographer: "John Seale", award: "Nominee" , koreanTitle: "매드 맥스: 분노의 도로" },
  { year: "2015", chineseTitle: "边境杀手", englishTitle: "Sicario", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "시카리오" },
  { year: "2014", chineseTitle: "鸟人", englishTitle: "Birdman: Or (The Unexpected Virtue of Ignorance)", cinematographer: "Emmanuel Lubezki", award: "Winner" , koreanTitle: "" },
  { year: "2014", chineseTitle: "布达佩斯大饭店", englishTitle: "The Grand Budapest Hotel", cinematographer: "Robert Yeoman", award: "Nominee" , koreanTitle: "그랜드 부다페스트 호텔" },
  { year: "2014", chineseTitle: "修女艾达", englishTitle: "Ida", cinematographer: "Łukasz Żal and Ryszard Lenczewski", award: "Nominee" , koreanTitle: "이다" },
  { year: "2014", chineseTitle: "透纳先生", englishTitle: "Mr. Turner", cinematographer: "Dick Pope", award: "Nominee" , koreanTitle: "미스터 터너" },
  { year: "2014", chineseTitle: "坚不可摧", englishTitle: "Unbroken", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "언브로큰" },
  { year: "2013", chineseTitle: "地心引力", englishTitle: "Gravity", cinematographer: "Emmanuel Lubezki", award: "Winner" , koreanTitle: "그래비티" },
  { year: "2013", chineseTitle: "一代宗师", englishTitle: "The Grandmaster", cinematographer: "Philippe Le Sourd", award: "Nominee" , koreanTitle: "" },
  { year: "2013", chineseTitle: "醉乡民谣", englishTitle: "Inside Llewyn Davis", cinematographer: "Bruno Delbonnel", award: "Nominee" , koreanTitle: "인사이드 르윈 데이비스" },
  { year: "2013", chineseTitle: "内布拉斯加", englishTitle: "Nebraska", cinematographer: "Phedon Papamichael", award: "Nominee" , koreanTitle: "네브래스카" },
  { year: "2013", chineseTitle: "失踪者", englishTitle: "Prisoners", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "프리즈너스" },
  { year: "2012", chineseTitle: "少年派的奇幻漂流", englishTitle: "Life of Pi", cinematographer: "Claudio Miranda", award: "Winner" , koreanTitle: "라이프 오브 파이" },
  { year: "2012", chineseTitle: "安娜·卡列尼娜", englishTitle: "Anna Karenina", cinematographer: "Seamus McGarvey", award: "Nominee" , koreanTitle: "안나 카레니나" },
  { year: "2012", chineseTitle: "被解放的姜戈", englishTitle: "Django Unchained", cinematographer: "Robert Richardson", award: "Nominee" , koreanTitle: "장고: 분노의 추적자" },
  { year: "2012", chineseTitle: "林肯", englishTitle: "Lincoln", cinematographer: "Janusz Kamiński", award: "Nominee" , koreanTitle: "링컨" },
  { year: "2012", chineseTitle: "007：大破天幕杀机", englishTitle: "Skyfall", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "스카이폴" },
  { year: "2011", chineseTitle: "雨果", englishTitle: "Hugo", cinematographer: "Robert Richardson", award: "Winner" , koreanTitle: "휴고" },
  { year: "2011", chineseTitle: "艺术家", englishTitle: "The Artist", cinematographer: "Guillaume Schiffman", award: "Nominee" , koreanTitle: "아티스트" },
  { year: "2011", chineseTitle: "放牛班的春天", englishTitle: "The Girl with the Dragon Tattoo", cinematographer: "Jeff Cronenweth", award: "Nominee" , koreanTitle: "" },
  { year: "2011", chineseTitle: "生命之树", englishTitle: "The Tree of Life", cinematographer: "Emmanuel Lubezki", award: "Nominee" , koreanTitle: "트리 오브 라이프" },
  { year: "2011", chineseTitle: "战马", englishTitle: "War Horse", cinematographer: "Janusz Kamiński", award: "Nominee" , koreanTitle: "워 호스" },
  { year: "2010", chineseTitle: "盗梦空间", englishTitle: "Inception", cinematographer: "Wally Pfister", award: "Winner" , koreanTitle: "인셉션" },
  { year: "2010", chineseTitle: "黑天鹅", englishTitle: "Black Swan", cinematographer: "Matthew Libatique", award: "Nominee" , koreanTitle: "" },
  { year: "2010", chineseTitle: "国王的演讲", englishTitle: "The King's Speech", cinematographer: "Danny Cohen", award: "Nominee" , koreanTitle: "" },
  { year: "2010", chineseTitle: "社交网络", englishTitle: "The Social Network", cinematographer: "Jeff Cronenweth", award: "Nominee" , koreanTitle: "" },
  { year: "2010", chineseTitle: "大地惊雷", englishTitle: "True Grit", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "더 브레이브" },
  { year: "2009", chineseTitle: "阿凡达", englishTitle: "Avatar", cinematographer: "Mauro Fiore", award: "Winner" , koreanTitle: "아바타" },
  { year: "2009", chineseTitle: "哈利·波特与混血王子", englishTitle: "Harry Potter and the Half-Blood Prince", cinematographer: "Bruno Delbonnel", award: "Nominee" , koreanTitle: "" },
  { year: "2009", chineseTitle: "拆弹部队", englishTitle: "The Hurt Locker", cinematographer: "Barry Ackroyd", award: "Nominee" , koreanTitle: "허트 로커" },
  { year: "2009", chineseTitle: "无耻混蛋", englishTitle: "Inglourious Basterds", cinematographer: "Robert Richardson", award: "Nominee" , koreanTitle: "바스터즈" },
  { year: "2009", chineseTitle: "白丝带", englishTitle: "The White Ribbon", cinematographer: "Christian Berger", award: "Nominee" , koreanTitle: "" },
  { year: "2008", chineseTitle: "贫民窟的百万富翁", englishTitle: "Slumdog Millionaire", cinematographer: "Anthony Dod Mantle", award: "Winner" , koreanTitle: "슬럼독 밀리어네어" },
  { year: "2008", chineseTitle: "换子疑云", englishTitle: "Changeling", cinematographer: "Tom Stern", award: "Nominee" , koreanTitle: "" },
  { year: "2008", chineseTitle: "本杰明·巴顿奇事", englishTitle: "The Curious Case of Benjamin Button", cinematographer: "Claudio Miranda", award: "Nominee" , koreanTitle: "벤자민 버튼의 시간은 거꾸로 간다" },
  { year: "2008", chineseTitle: "蝙蝠侠：黑暗骑士", englishTitle: "The Dark Knight", cinematographer: "Wally Pfister", award: "Nominee" , koreanTitle: "다크 나이트" },
  { year: "2008", chineseTitle: "朗读者", englishTitle: "The Reader", cinematographer: "Roger Deakins and Chris Menges", award: "Nominee" , koreanTitle: "더 리더" },
  { year: "2007", chineseTitle: "心血来潮", englishTitle: "There Will be Blood", cinematographer: "Robert Elswit", award: "Winner" , koreanTitle: "" },
  { year: "2007", chineseTitle: "珍珠港", englishTitle: "The Assassination of Jesse James", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "" },
  { year: "2007", chineseTitle: "赎罪", englishTitle: "Atonement", cinematographer: "Seamus McGarvey", award: "Nominee" , koreanTitle: "어톤먼트" },
  { year: "2007", chineseTitle: "潜水钟与蝴蝶", englishTitle: "The Diving Bell and the Butterfly", cinematographer: "Janusz Kamiński", award: "Nominee" , koreanTitle: "잠수종과 나비" },
  { year: "2007", chineseTitle: "老无所依", englishTitle: "No Country for Old Men", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "노인을 위한 나라는 없다" },
  { year: "2006", chineseTitle: "潘神的迷宫", englishTitle: "Pan’s Labyrinth", cinematographer: "Guillermo Navarro", award: "Winner" , koreanTitle: "" },
  { year: "2006", chineseTitle: "黑色夜魔女", englishTitle: "The Black Dahlia", cinematographer: "Vilmos Zsigmond", award: "Nominee" , koreanTitle: "" },
  { year: "2006", chineseTitle: "人类之子", englishTitle: "Children of Men", cinematographer: "Emmanuel Lubezki", award: "Nominee" , koreanTitle: "칠드런 오브 맨" },
  { year: "2006", chineseTitle: "变魔术师", englishTitle: "The Illusionist", cinematographer: "Dick Pope", award: "Nominee" , koreanTitle: "" },
  { year: "2006", chineseTitle: "致命魔术", englishTitle: "The Prestige", cinematographer: "Wally Pfister", award: "Nominee" , koreanTitle: "더 프레스티지" },
  { year: "2005", chineseTitle: "艺伎回忆录", englishTitle: "Memoirs of a Geisha", cinematographer: "Dion Beebe", award: "Winner" , koreanTitle: "게이샤의 추억" },
  { year: "2005", chineseTitle: "蝙蝠侠：侠影之谜", englishTitle: "Batman Begins", cinematographer: "Wally Pfister", award: "Nominee" , koreanTitle: "배트맨 비긴즈" },
  { year: "2005", chineseTitle: "断背山", englishTitle: "Brokeback Mountain", cinematographer: "Rodrigo Prieto", award: "Nominee" , koreanTitle: "브로크백 마운틴" },
  { year: "2005", chineseTitle: "晚安，好运", englishTitle: "Good Night and Good Luck", cinematographer: "Robert Elswit", award: "Nominee" , koreanTitle: "" },
  { year: "2005", chineseTitle: "新世界", englishTitle: "The New World", cinematographer: "Emmanuel Lubezki", award: "Nominee" , koreanTitle: "뉴 월드" },
  { year: "2004", chineseTitle: "飞行家", englishTitle: "The Aviator", cinematographer: "Robert Richardson", award: "Winner" , koreanTitle: "에비에이터" },
  { year: "2004", chineseTitle: "十面埋伏", englishTitle: "House of Flying Daggers", cinematographer: "Zhao Xiaoding", award: "Nominee" , koreanTitle: "십면매복" },
  { year: "2004", chineseTitle: "基督受难记", englishTitle: "The Passion of the Christ", cinematographer: "Caleb Deschanel", award: "Nominee" , koreanTitle: "패션 오브 더 크라이스트" },
  { year: "2004", chineseTitle: "歌剧魅影", englishTitle: "The Phantom of the Opera", cinematographer: "John Mathieson", award: "Nominee" , koreanTitle: "오페라의 유령" },
  { year: "2004", chineseTitle: "漫长的婚约", englishTitle: "A Very Long Engagement", cinematographer: "Bruno Delbonnel", award: "Nominee" , koreanTitle: "영원한 약속" },
  { year: "2003", chineseTitle: "霸王别姬", englishTitle: "Master and Commander", cinematographer: "Russell Boyd", award: "Winner" , koreanTitle: "" },
  { year: "2003", chineseTitle: "上帝之城", englishTitle: "City of God", cinematographer: "César Charlone", award: "Nominee" , koreanTitle: "시티 오브 갓" },
  { year: "2003", chineseTitle: "寒冷山脉", englishTitle: "Cold Mountain", cinematographer: "John Seale", award: "Nominee" , koreanTitle: "" },
  { year: "2003", chineseTitle: "戴珍珠耳环的少女", englishTitle: "Girl with a Pearl Earring", cinematographer: "Eduardo Serra", award: "Nominee" , koreanTitle: "진주 귀걸이를 한 소녀" },
  { year: "2003", chineseTitle: "美国田园风光", englishTitle: "Seabiscuit", cinematographer: "John Schwartzman", award: "Nominee" , koreanTitle: "" },
  { year: "2002", chineseTitle: "破碎之路", englishTitle: "Road to Perdition", cinematographer: "Conrad Hall (posthumously)", award: "Winner" , koreanTitle: "로드 투 퍼디션" },
  { year: "2002", chineseTitle: "逐梦女郎", englishTitle: "Chicago", cinematographer: "Dion Beebe", award: "Nominee" , koreanTitle: "시카고" },
  { year: "2002", chineseTitle: "远离天堂", englishTitle: "Far From Heaven", cinematographer: "Edward Lachman", award: "Nominee" , koreanTitle: "" },
  { year: "2002", chineseTitle: "纽约黑帮", englishTitle: "Gangs of New York", cinematographer: "Michael Ballhaus", award: "Nominee" , koreanTitle: "갱스 오브 뉴욕" },
  { year: "2002", chineseTitle: "钢琴家", englishTitle: "The Pianist", cinematographer: "Paweł Edelman", award: "Nominee" , koreanTitle: "피아니스트" },
  { year: "2001", chineseTitle: "魔戒首部曲：护戒使者", englishTitle: "The Lord of the Rings: The Fellowship of the Ring", cinematographer: "Andrew Lesnie", award: "Winner" , koreanTitle: "반지의 제왕: 반지 원정대" },
  { year: "2001", chineseTitle: "天使爱美丽", englishTitle: "Amélie", cinematographer: "Bruno Delbonnel", award: "Nominee" , koreanTitle: "아멜리에" },
  { year: "2001", chineseTitle: "黑鹰坠落", englishTitle: "Black Hawk Down", cinematographer: "Sławomir Idziak", award: "Nominee" , koreanTitle: "블랙 호크 다운" },
  { year: "2001", chineseTitle: "缺席的人", englishTitle: "The Man Who Wasn’t There", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "" },
  { year: "2001", chineseTitle: "红磨坊", englishTitle: "Moulin Rouge", cinematographer: "Donald McAlpine", award: "Nominee" , koreanTitle: "" },
  { year: "2000", chineseTitle: "卧虎藏龙", englishTitle: "Crouching Tiger, Hidden Dragon", cinematographer: "Peter Pau", award: "Winner" , koreanTitle: "와호장룡" },
  { year: "2000", chineseTitle: "角斗士", englishTitle: "Gladiator", cinematographer: "John Mathieson", award: "Nominee" , koreanTitle: "글래디에이터" },
  { year: "2000", chineseTitle: "玛莲娜", englishTitle: "Malèna", cinematographer: "Lajos Koltai", award: "Nominee" , koreanTitle: "말레나" },
  { year: "2000", chineseTitle: "逃狱三王", englishTitle: "O Brother, Where Art Thou", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "" },
  { year: "2000", chineseTitle: "爱国者", englishTitle: "The Patriot", cinematographer: "Caleb Deschanel", award: "Nominee" , koreanTitle: "패트리어트" },
  { year: "1999", chineseTitle: "美国丽人", englishTitle: "American Beauty", cinematographer: "Conrad L. Hall", award: "Winner" , koreanTitle: "아메리칸 뷰티" },
  { year: "1999", chineseTitle: "爱到尽头", englishTitle: "The End of the Affair", cinematographer: "Roger Pratt", award: "Nominee" , koreanTitle: "사랑의 종말" },
  { year: "1999", chineseTitle: "惊爆内幕", englishTitle: "The Insider", cinematographer: "Dante Spinotti", award: "Nominee" , koreanTitle: "" },
  { year: "1999", chineseTitle: "断头谷", englishTitle: "Sleepy Hollow", cinematographer: "Emmanuel Lubezki", award: "Nominee" , koreanTitle: "슬리피 할로우" },
  { year: "1999", chineseTitle: "雪落在雪松上", englishTitle: "Snow Falling on Cedars", cinematographer: "Robert Richardson", award: "Nominee" , koreanTitle: "시더스의 눈" },
  { year: "1998", chineseTitle: "拯救大兵瑞恩", englishTitle: "Saving Private Ryan", cinematographer: "Janusz Kamiński", award: "Winner" , koreanTitle: "라이언 일병 구하기" },
  { year: "1998", chineseTitle: "民事公诉", englishTitle: "A Civil Action", cinematographer: "Conrad L. Hall", award: "Nominee" , koreanTitle: "" },
  { year: "1998", chineseTitle: "伊丽莎白", englishTitle: "Elizabeth", cinematographer: "Remi Adefarasin", award: "Nominee" , koreanTitle: "엘리자베스" },
  { year: "1998", chineseTitle: "莎士比亚情史", englishTitle: "Shakespeare in Love", cinematographer: "Richard Greatrex", award: "Nominee" , koreanTitle: "셰익스피어 인 러브" },
  { year: "1998", chineseTitle: "细细的红线", englishTitle: "The Thin Red Line", cinematographer: "John Toll", award: "Nominee" , koreanTitle: "씬 레드 라인" },
  { year: "1997", chineseTitle: "泰坦尼克号", englishTitle: "Titanic", cinematographer: "Russell Carpenter", award: "Winner" , koreanTitle: "타이타닉" },
  { year: "1997", chineseTitle: "安米斯塔德号", englishTitle: "Amistad", cinematographer: "Janusz Kamiński", award: "Nominee" , koreanTitle: "아미스타드" },
  { year: "1997", chineseTitle: "昆顿", englishTitle: "Kundun", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "쿤둔" },
  { year: "1997", chineseTitle: "L.A.机密档案", englishTitle: "L.A. Confidential", cinematographer: "Dante Spinotti", award: "Nominee" , koreanTitle: "LA 컨피덴셜" },
  { year: "1997", chineseTitle: "鸽之翼", englishTitle: "The Wings of the Dove", cinematographer: "Eduardo Serra", award: "Nominee" , koreanTitle: "비둘기의 날개" },
  { year: "1996", chineseTitle: "英国病人", englishTitle: "The English Patient", cinematographer: "John Seale", award: "Winner" , koreanTitle: "잉글리쉬 페이션트" },
  { year: "1996", chineseTitle: "艾薇塔", englishTitle: "Evita", cinematographer: "Darius Khondji", award: "Nominee" , koreanTitle: "에비타" },
  { year: "1996", chineseTitle: "法高", englishTitle: "Fargo", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "파고" },
  { year: "1996", chineseTitle: "走向自由", englishTitle: "Fly Away Home", cinematographer: "Caleb Deschanel", award: "Nominee" , koreanTitle: "플라이 어웨이 홈" },
  { year: "1996", chineseTitle: "迈克尔·柯林斯", englishTitle: "Michael Collins", cinematographer: "Chris Menges", award: "Nominee" , koreanTitle: "" },
  { year: "1995", chineseTitle: "勇敢的心", englishTitle: "Braveheart", cinematographer: "John Toll", award: "Winner" , koreanTitle: "브레이브하트" },
  { year: "1995", chineseTitle: "蝙蝠侠前传", englishTitle: "Batman Forever", cinematographer: "Stephen Goldblatt", award: "Nominee" , koreanTitle: "배트맨 포에버" },
  { year: "1995", chineseTitle: "小公主", englishTitle: "A Little Princess", cinematographer: "Emmanuel Lubezki", award: "Nominee" , koreanTitle: "작은 공주" },
  { year: "1995", chineseTitle: "理智与情感", englishTitle: "Sense and Sensibility", cinematographer: "Michael Coulter", award: "Nominee" , koreanTitle: "센스 앤 센서빌리티" },
  { year: "1995", chineseTitle: "摇滚青年", englishTitle: "Shanghai Triad", cinematographer: "Lü Yue", award: "Nominee" , koreanTitle: "" },
  { year: "1994", chineseTitle: "落日余晖", englishTitle: "Legends of the Fall", cinematographer: "John Toll", award: "Winner" , koreanTitle: "가을의 전설" },
  { year: "1994", chineseTitle: "阿甘正传", englishTitle: "Forrest Gump", cinematographer: "Don Burgess", award: "Nominee" , koreanTitle: "" },
  { year: "1994", chineseTitle: "肖申克的救赎", englishTitle: "The Shawshank Redemption", cinematographer: "Roger Deakins", award: "Nominee" , koreanTitle: "쇼생크 탈출" },
  { year: "1994", chineseTitle: "蓝白红三部曲之红", englishTitle: "Three Colours: Red", cinematographer: "Piotr Sobociński", award: "Nominee" , koreanTitle: "" },
  { year: "1994", chineseTitle: "怀特·厄普", englishTitle: "Wyatt Earp", cinematographer: "Owen Roizman", award: "Nominee" , koreanTitle: "" },
  { year: "1993", chineseTitle: "辛德勒的名单", englishTitle: "Schindler’s List", cinematographer: "Janusz Kamiński", award: "Winner" , koreanTitle: "" },
  { year: "1993", chineseTitle: "霸王别姬", englishTitle: "Farewell My Concubine", cinematographer: "Gu Changwei", award: "Nominee" , koreanTitle: "" },
  { year: "1993", chineseTitle: "逃犯", englishTitle: "The Fugitive", cinematographer: "Michael Chapman", award: "Nominee" , koreanTitle: "" },
  { year: "1993", chineseTitle: "钢琴师", englishTitle: "The Piano", cinematographer: "Stuart Dryburgh", award: "Nominee" , koreanTitle: "" },
  { year: "1993", chineseTitle: "寻找鲍比·费舍尔", englishTitle: "Searching for Bobby Fischer", cinematographer: "Conrad L. Hall", award: "Nominee" , koreanTitle: "" },
  { year: "1992", chineseTitle: "大河恋", englishTitle: "A River Runs Through It", cinematographer: "Philippe Rousselot", award: "Winner" , koreanTitle: "" },
  { year: "1992", chineseTitle: "霍法", englishTitle: "Hoffa", cinematographer: "Stephen H. Burum", award: "Nominee" , koreanTitle: "" },
  { year: "1992", chineseTitle: "霍华德庄园", englishTitle: "Howards End", cinematographer: "Tony Pierce-Roberts", award: "Nominee" , koreanTitle: "" },
  { year: "1992", chineseTitle: "情人", englishTitle: "The Lover", cinematographer: "Robert Fraisse", award: "Nominee" , koreanTitle: "" },
  { year: "1992", chineseTitle: "无法原谅", englishTitle: "Unforgiven", cinematographer: "Jack N. Green", award: "Nominee" , koreanTitle: "" },
  { year: "1991", chineseTitle: "肯尼迪总统遇刺案", englishTitle: "JFK", cinematographer: "Robert Richardson", award: "Winner" , koreanTitle: "" },
  { year: "1991", chineseTitle: "豪情四海", englishTitle: "Bugsy", cinematographer: "Allen Daviau", award: "Nominee" , koreanTitle: "" },
  { year: "1991", chineseTitle: "潮浪王子", englishTitle: "The Prince of Tides", cinematographer: "Stephen Goldblatt", award: "Nominee" , koreanTitle: "" },
  { year: "1991", chineseTitle: "终结者2：审判日", englishTitle: "Terminator 2: Judgement Day", cinematographer: "Adam Greenberg", award: "Nominee" , koreanTitle: "" },
  { year: "1991", chineseTitle: "末路狂花", englishTitle: "Thelma & Louise", cinematographer: "Adrian Biddle", award: "Nominee" , koreanTitle: "" },
  { year: "1990", chineseTitle: "与狼共舞", englishTitle: "Dances with Wolves", cinematographer: "Dean Semler", award: "Winner" , koreanTitle: "" },
  { year: "1990", chineseTitle: "阿瓦隆", englishTitle: "Avalon", cinematographer: "Allen Daviau", award: "Nominee" , koreanTitle: "" },
  { year: "1990", chineseTitle: "迪克·特雷西", englishTitle: "Dick Tracy", cinematographer: "Vittorio Storaro", award: "Nominee" , koreanTitle: "" },
  { year: "1990", chineseTitle: "教父3", englishTitle: "The Godfather: Part III", cinematographer: "Gordon Willis", award: "Nominee" , koreanTitle: "" },
  { year: "1990", chineseTitle: "亨利与朱恩", englishTitle: "Henry & June", cinematographer: "Philippe Rousselot", award: "Nominee" , koreanTitle: "" },
  { year: "1989", chineseTitle: "荣耀", englishTitle: "Glory", cinematographer: "Freddie Francis", award: "Winner" , koreanTitle: "" },
  { year: "1989", chineseTitle: "深渊", englishTitle: "The Abyss", cinematographer: "Mikael Salomon", award: "Nominee" , koreanTitle: "" },
  { year: "1989", chineseTitle: "火焰", englishTitle: "Blaze", cinematographer: "Haskell Wexler", award: "Nominee" , koreanTitle: "" },
  { year: "1989", chineseTitle: "第四洲出生", englishTitle: "Born on the Fourth of July", cinematographer: "Robert Richardson", award: "Nominee" , koreanTitle: "" },
  { year: "1989", chineseTitle: "一曲相思情未了", englishTitle: "The Fabulous Baker Boys", cinematographer: "Michael Ballhaus", award: "Nominee" , koreanTitle: "" },
  { year: "1988", chineseTitle: "密西西比燃烧的黎明", englishTitle: "Mississippi Burning", cinematographer: "Peter Biziou", award: "Winner" , koreanTitle: "" },
  { year: "1988", chineseTitle: "雨人", englishTitle: "Rain Man", cinematographer: "John Seale", award: "Nominee" , koreanTitle: "" },
  { year: "1988", chineseTitle: "墨西哥日出", englishTitle: "Tequila Sunrise", cinematographer: "Conrad Hall", award: "Nominee" , koreanTitle: "" },
  { year: "1988", chineseTitle: "生命的不可承受之轻", englishTitle: "The Unbearable Lightness of Being", cinematographer: "Sven Nykvist", award: "Nominee" , koreanTitle: "" },
  { year: "1988", chineseTitle: "非常疑犯", englishTitle: "Who Framed Roger Rabbit", cinematographer: "Dean Cundey", award: "Nominee" , koreanTitle: "" },
  { year: "1987", chineseTitle: "末代皇帝", englishTitle: "The Last Emperor", cinematographer: "Vittorio Storaro", award: "Winner" , koreanTitle: "" },
  { year: "1987", chineseTitle: "广播新闻", englishTitle: "Broadcast News", cinematographer: "Michael Ballhaus", award: "Nominee" , koreanTitle: "" },
  { year: "1987", chineseTitle: "阳光帝国", englishTitle: "Empire of the Sun", cinematographer: "Allen Daviau", award: "Nominee" , koreanTitle: "" },
  { year: "1987", chineseTitle: "希望和荣耀", englishTitle: "Hope and Glory", cinematographer: "Philippe Rousselot", award: "Nominee" , koreanTitle: "" },
  { year: "1987", chineseTitle: "梅特万", englishTitle: "Matewan", cinematographer: "Haskell Wexler", award: "Nominee" , koreanTitle: "" },
  { year: "1986", chineseTitle: "宣教的使命", englishTitle: "The Mission", cinematographer: "Chris Menges", award: "Winner" , koreanTitle: "" },
  { year: "1986", chineseTitle: "佩吉苏的婚礼", englishTitle: "Peggy Sue Got Married", cinematographer: "Jordan Cronenweth", award: "Nominee" , koreanTitle: "" },
  { year: "1986", chineseTitle: "新兵小子", englishTitle: "Platoon", cinematographer: "Robert Richardson", award: "Nominee" , koreanTitle: "" },
  { year: "1986", chineseTitle: "观景房", englishTitle: "A Room with a View", cinematographer: "Tony Pierce-Roberts", award: "Nominee" , koreanTitle: "" },
  { year: "1986", chineseTitle: "星际迷航4：返乡", englishTitle: "Star Trek IV: The Voyage Home", cinematographer: "Don Peterman", award: "Nominee" , koreanTitle: "" },
  { year: "1985", chineseTitle: "走出非洲", englishTitle: "Out Of Africa", cinematographer: "David Watkin", award: "Winner" , koreanTitle: "" },
  { year: "1985", chineseTitle: "紫色", englishTitle: "The Color Purple", cinematographer: "Allen Daviau", award: "Nominee" , koreanTitle: "" },
  { year: "1985", chineseTitle: "爱情与浪漫", englishTitle: "Murphy's Romance", cinematographer: "William A. Fraker", award: "Nominee" , koreanTitle: "" },
  { year: "1985", chineseTitle: "乱", englishTitle: "Ran", cinematographer: "Takao Saito, Masaharu Ueda, and Asakazu Nakai", award: "Nominee" , koreanTitle: "" },
  { year: "1985", chineseTitle: "目击者", englishTitle: "Witness", cinematographer: "John Seale", award: "Nominee" , koreanTitle: "" },
  { year: "1984", chineseTitle: "殺戮的黃田", englishTitle: "The Killing Fields", cinematographer: "Chris Menges", award: "Winner" , koreanTitle: "" },
  { year: "1984", chineseTitle: "亚马逊的神", englishTitle: "Amadeus", cinematographer: "Miroslav Ondříček", award: "Nominee" , koreanTitle: "" },
  { year: "1984", chineseTitle: "天生的球星", englishTitle: "The Natural", cinematographer: "Caleb Deschanel", award: "Nominee" , koreanTitle: "" },
  { year: "1984", chineseTitle: "印度之路", englishTitle: "A Passage to India", cinematographer: "Ernest Day", award: "Nominee" , koreanTitle: "" },
  { year: "1984", chineseTitle: "河流", englishTitle: "The River", cinematographer: "Vilmos Zsigmond", award: "Nominee" , koreanTitle: "" },
  { year: "1983", chineseTitle: "法尼和亚历山大", englishTitle: "Fanny and Alexander", cinematographer: "Sven Nykvist", award: "Winner" , koreanTitle: "" },
  { year: "1983", chineseTitle: "热舞情人", englishTitle: "Flashdance", cinematographer: "Don Peterman", award: "Nominee" , koreanTitle: "" },
  { year: "1983", chineseTitle: "正确的东西", englishTitle: "The Right Stuff", cinematographer: "Caleb Deschanel", award: "Nominee" , koreanTitle: "" },
  { year: "1983", chineseTitle: "战争游戏", englishTitle: "War Games", cinematographer: "William A. Fraker", award: "Nominee" , koreanTitle: "" },
  { year: "1983", chineseTitle: "导演大师", englishTitle: "Zelig", cinematographer: "Gordon Willis", award: "Nominee" , koreanTitle: "" },
  { year: "1982", chineseTitle: "甘地", englishTitle: "Gandhi", cinematographer: "Billy Williams and Ronnie Taylor", award: "Winner" , koreanTitle: "" },
  { year: "1982", chineseTitle: "潜艇", englishTitle: "Das Boot", cinematographer: "Jost Vacano", award: "Nominee" , koreanTitle: "" },
  { year: "1982", chineseTitle: "外星人", englishTitle: "E.T. the Extra-Terrestrial", cinematographer: "Allen Daviau", award: "Nominee" , koreanTitle: "" },
  { year: "1982", chineseTitle: "苏菲的抉择", englishTitle: "Sophie's Choice", cinematographer: "Néstor Almendros", award: "Nominee" , koreanTitle: "" },
  { year: "1982", chineseTitle: "泰尼", englishTitle: "Tootsie", cinematographer: "Owen Roizman", award: "Nominee" , koreanTitle: "" },
  { year: "1981", chineseTitle: "红色之心", englishTitle: "Reds", cinematographer: "Vittorio Storaro", award: "Winner" , koreanTitle: "" },
  { year: "1981", chineseTitle: "剑神", englishTitle: "Excalibur", cinematographer: "Alex Thomson", award: "Nominee" , koreanTitle: "" },
  { year: "1981", chineseTitle: "黄金池塘", englishTitle: "On Golden Pond", cinematographer: "Billy Williams", award: "Nominee" , koreanTitle: "" },
  { year: "1981", chineseTitle: "流行音乐", englishTitle: "Ragtime", cinematographer: "Miroslav Ondříček", award: "Nominee" , koreanTitle: "" },
  { year: "1981", chineseTitle: "夺宝奇兵", englishTitle: "Raiders of the Lost Ark", cinematographer: "Douglas Slocombe", award: "Nominee" , koreanTitle: "" },
  { year: "1980", chineseTitle: "泰斯", englishTitle: "Tess", cinematographer: "Geoffrey Unsworth (posthumously) and Ghislain Cloquet", award: "Winner" , koreanTitle: "" },
  { year: "1980", chineseTitle: "蓝色珊瑚礁", englishTitle: "The Blue Lagoon", cinematographer: "Néstor Almendros", award: "Nominee" , koreanTitle: "" },
  { year: "1980", chineseTitle: "矿工之女", englishTitle: "Coal Miner's Daughter", cinematographer: "Ralf D. Bode", award: "Nominee" , koreanTitle: "" },
  { year: "1980", chineseTitle: "大追捕", englishTitle: "The Formula", cinematographer: "James Crabe", award: "Nominee" , koreanTitle: "" },
  { year: "1980", chineseTitle: "愤怒的公牛", englishTitle: "Raging Bull", cinematographer: "Michael Chapman", award: "Nominee" , koreanTitle: "" },
  { year: "1979", chineseTitle: "现代启示录", englishTitle: "Apocalypse Now", cinematographer: "Vittorio Storaro", award: "Winner" , koreanTitle: "" },
  { year: "1979", chineseTitle: "1941年", englishTitle: "1941", cinematographer: "William A. Fraker", award: "Nominee" , koreanTitle: "" },
  { year: "1979", chineseTitle: "秀场才子", englishTitle: "All That Jazz", cinematographer: "Giuseppe Rotunno", award: "Nominee" , koreanTitle: "" },
  { year: "1979", chineseTitle: "黑洞", englishTitle: "The Black Hole", cinematographer: "Frank V. Phillips", award: "Nominee" , koreanTitle: "" },
  { year: "1979", chineseTitle: "克莱默对克莱默", englishTitle: "Kramer vs. Kramer", cinematographer: "Néstor Almendros", award: "Nominee" , koreanTitle: "" },
  { year: "1978", chineseTitle: "天国之日", englishTitle: "Days of Heaven", cinematographer: "Néstor Almendros", award: "Winner" , koreanTitle: "" },
  { year: "1978", chineseTitle: "猎鹿人", englishTitle: "The Deer Hunter", cinematographer: "Vilmos Zsigmond", award: "Nominee" , koreanTitle: "" },
  { year: "1978", chineseTitle: "天堂可以等待", englishTitle: "Heaven Can Wait", cinematographer: "William A. Fraker", award: "Nominee" , koreanTitle: "" },
  { year: "1978", chineseTitle: "明年此时", englishTitle: "Same Time, Next Year", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1978", chineseTitle: "魔幻巫师", englishTitle: "The Wiz", cinematographer: "Oswald Morris", award: "Nominee" , koreanTitle: "" },
  { year: "1977", chineseTitle: "第三维度的接触", englishTitle: "Close Encounters of the Third Kind", cinematographer: "Vilmos Zsigmond", award: "Winner" , koreanTitle: "" },
  { year: "1977", chineseTitle: "海锁金山", englishTitle: "Islands in the Stream", cinematographer: "Fred J. Koenekamp", award: "Nominee" , koreanTitle: "" },
  { year: "1977", chineseTitle: "茱莉亚", englishTitle: "Julia", cinematographer: "Douglas Slocombe", award: "Nominee" , koreanTitle: "" },
  { year: "1977", chineseTitle: "寻找好吧台先生", englishTitle: "Looking for Mr. Goodbar", cinematographer: "William A. Fraker", award: "Nominee" , koreanTitle: "" },
  { year: "1977", chineseTitle: "转折点", englishTitle: "The Turning Point", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1976", chineseTitle: "向着荣耀前行", englishTitle: "Bound for Glory", cinematographer: "Haskell Wexler", award: "Winner" , koreanTitle: "" },
  { year: "1976", chineseTitle: "金刚", englishTitle: "King Kong", cinematographer: "Richard H. Kline", award: "Nominee" , koreanTitle: "" },
  { year: "1976", chineseTitle: "天网杀机", englishTitle: "Logan's Run", cinematographer: "Ernest Laszlo", award: "Nominee" , koreanTitle: "" },
  { year: "1976", chineseTitle: "变相怪杰", englishTitle: "Network", cinematographer: "Owen Roizman", award: "Nominee" , koreanTitle: "" },
  { year: "1976", chineseTitle: "一颗明星闪耀", englishTitle: "A Star Is Born", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "스타 이즈 본" },
  { year: "1975", chineseTitle: "巴里•林登", englishTitle: "Barry Lyndon", cinematographer: "John Alcott", award: "Winner" , koreanTitle: "" },
  { year: "1975", chineseTitle: "蝗虫的日子", englishTitle: "The Day of the Locust", cinematographer: "Conrad Hall", award: "Nominee" , koreanTitle: "" },
  { year: "1975", chineseTitle: "滑稽的女士", englishTitle: "Funny Lady", cinematographer: "James Wong Howe", award: "Nominee" , koreanTitle: "" },
  { year: "1975", chineseTitle: "金德堡号", englishTitle: "The Hindenburg", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1975", chineseTitle: "飞越疯人院", englishTitle: "One Flew Over the Cuckoo's Nest", cinematographer: "Haskell Wexler and Bill Butler", award: "Nominee" , koreanTitle: "" },
  { year: "1974", chineseTitle: "摩天火灾", englishTitle: "The Towering Inferno", cinematographer: "Fred J. Koenekamp and Joseph Biroc", award: "Winner" , koreanTitle: "" },
  { year: "1974", chineseTitle: "唐人街", englishTitle: "Chinatown", cinematographer: "John A. Alonzo", award: "Nominee" , koreanTitle: "" },
  { year: "1974", chineseTitle: "地震", englishTitle: "Earthquake", cinematographer: "Philip H. Lathrop", award: "Nominee" , koreanTitle: "" },
  { year: "1974", chineseTitle: "莱尼", englishTitle: "Lenny", cinematographer: "Bruce Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1974", chineseTitle: "东方快车谋杀案", englishTitle: "Murder on the Orient Express", cinematographer: "Geoffrey Unsworth", award: "Nominee" , koreanTitle: "" },
  { year: "1973", chineseTitle: "哭泣与低语", englishTitle: "Cries and Whispers", cinematographer: "Sven Nykvist", award: "Winner" , koreanTitle: "" },
  { year: "1973", chineseTitle: "驱魔人", englishTitle: "The Exorcist", cinematographer: "Owen Roizman", award: "Nominee" , koreanTitle: "" },
  { year: "1973", chineseTitle: "乔纳森·利文斯顿海鸥", englishTitle: "Jonathan Livingston Seagull", cinematographer: "Jack Couffer", award: "Nominee" , koreanTitle: "" },
  { year: "1973", chineseTitle: "刺针", englishTitle: "The Sting", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1973", chineseTitle: "往日情怀", englishTitle: "The Way We Were", cinematographer: "Harry Stradling Jr.", award: "Nominee" , koreanTitle: "" },
  { year: "1972", chineseTitle: "歌舞表演", englishTitle: "Cabaret", cinematographer: "Geoffrey Unsworth", award: "Winner" , koreanTitle: "" },
  { year: "1972", chineseTitle: "1776年", englishTitle: "1776", cinematographer: "Harry Stradling Jr.", award: "Nominee" , koreanTitle: "" },
  { year: "1972", chineseTitle: "蝴蝶自由了", englishTitle: "Butterflies Are Free", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1972", chineseTitle: "波塞冬号大冒险", englishTitle: "The Poseidon Adventure", cinematographer: "Harold E. Stine", award: "Nominee" , koreanTitle: "" },
  { year: "1972", chineseTitle: "与姑姑的旅行", englishTitle: "Travels with My Aunt", cinematographer: "Douglas Slocombe", award: "Nominee" , koreanTitle: "" },
  { year: "1971", chineseTitle: "屋顶上的小提琴手", englishTitle: "Fiddler on the Roof", cinematographer: "Oswald Morris", award: "Winner" , koreanTitle: "" },
  { year: "1971", chineseTitle: "法国贩毒网络", englishTitle: "The French Connection", cinematographer: "Owen Roizman", award: "Nominee" , koreanTitle: "" },
  { year: "1971", chineseTitle: "最后一次放映", englishTitle: "The Last Picture Show", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1971", chineseTitle: "尼古拉斯和亚历山德拉", englishTitle: "Nicholas and Alexandra", cinematographer: "Freddie Young", award: "Nominee" , koreanTitle: "" },
  { year: "1971", chineseTitle: "42年夏天", englishTitle: "Summer of '42", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1970", chineseTitle: "瑞恩的女儿", englishTitle: "Ryan's Daughter", cinematographer: "Freddie Young", award: "Winner" , koreanTitle: "" },
  { year: "1970", chineseTitle: "机场", englishTitle: "Airport", cinematographer: "Ernest Laszlo", award: "Nominee" , koreanTitle: "" },
  { year: "1970", chineseTitle: "帕顿", englishTitle: "Patton", cinematographer: "Fred J. Koenekamp", award: "Nominee" , koreanTitle: "" },
  { year: "1970", chineseTitle: "虎！虎！虎！", englishTitle: "Tora! Tora! Tora!", cinematographer: "Osami Furuya, Sinsaku Himeda, Masamichi Satoh and Charles F. Wheeler", award: "Nominee" , koreanTitle: "" },
  { year: "1970", chineseTitle: "恋爱中的女人", englishTitle: "Women in Love", cinematographer: "Billy Williams", award: "Nominee" , koreanTitle: "" },
  { year: "1969", chineseTitle: "跑车兄弟", englishTitle: "Butch Cassidy and the Sundance Kid", cinematographer: "Conrad Hall", award: "Winner" , koreanTitle: "" },
  { year: "1969", chineseTitle: "千日安妮", englishTitle: "Anne of the Thousand Days", cinematographer: "Arthur Ibbetson", award: "Nominee" , koreanTitle: "" },
  { year: "1969", chineseTitle: "鲍勃和卡罗尔和特德和艾丽斯", englishTitle: "Bob & Carol & Ted & Alice", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1969", chineseTitle: "你好,多莉!", englishTitle: "Hello, Dolly!", cinematographer: "Harry Stradling (posthumously)", award: "Nominee" , koreanTitle: "" },
  { year: "1969", chineseTitle: "被困", englishTitle: "Marooned", cinematographer: "Daniel L. Fapp", award: "Nominee" , koreanTitle: "" },
  { year: "1968", chineseTitle: "罗密欧与朱丽叶", englishTitle: "Romeo and Juliet", cinematographer: "Pasqualino De Santis", award: "Winner" , koreanTitle: "" },
  { year: "1968", chineseTitle: "滑稽女孩", englishTitle: "Funny Girl", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1968", chineseTitle: "大北极", englishTitle: "Ice Station Zebra", cinematographer: "Daniel L. Fapp", award: "Nominee" , koreanTitle: "" },
  { year: "1968", chineseTitle: "奥利弗!", englishTitle: "Oliver!", cinematographer: "Oswald Morris", award: "Nominee" , koreanTitle: "" },
  { year: "1968", chineseTitle: "明星!", englishTitle: "Star!", cinematographer: "Ernest Laszlo", award: "Nominee" , koreanTitle: "" },
  { year: "1967", chineseTitle: "邦妮和克莱德", englishTitle: "Bonnie and Clyde", cinematographer: "Burnett Guffey", award: "Winner" , koreanTitle: "" },
  { year: "1967", chineseTitle: "骑士国度", englishTitle: "Camelot", cinematographer: "Richard H. Kline", award: "Nominee" , koreanTitle: "" },
  { year: "1967", chineseTitle: "动物医生", englishTitle: "Doctor Dolittle", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1967", chineseTitle: "毕业生", englishTitle: "The Graduate", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1967", chineseTitle: "冷血杀人事件", englishTitle: "In Cold Blood", cinematographer: "Conrad Hall", award: "Nominee" , koreanTitle: "" },
  { year: "1966", chineseTitle: "谁害怕弗吉尼亚伍尔夫?", englishTitle: "Who's Afraid of Virginia Woolf?", cinematographer: "Haskell Wexler", award: "Winner" , koreanTitle: "" },
  { year: "1966", chineseTitle: "幸运曲奇", englishTitle: "The Fortune Cookie", cinematographer: "Joseph LaShelle", award: "Nominee" , koreanTitle: "" },
  { year: "1966", chineseTitle: "乔琪女孩", englishTitle: "Georgy Girl", cinematographer: "Kenneth Higgins", award: "Nominee" , koreanTitle: "" },
  { year: "1966", chineseTitle: "巴黎在燃烧吗？", englishTitle: "Is Paris Burning?", cinematographer: "Marcel Grignon", award: "Nominee" , koreanTitle: "" },
  { year: "1966", chineseTitle: "第二次机会", englishTitle: "Seconds", cinematographer: "James Wong Howe", award: "Nominee" , koreanTitle: "" },
  { year: "1966", chineseTitle: "日月精忠", englishTitle: "A Man for All Seasons", cinematographer: "Ted Moore", award: "Winner" , koreanTitle: "" },
  { year: "1966", chineseTitle: "奇幻航行", englishTitle: "Fantastic Voyage", cinematographer: "Ernest Laszlo", award: "Nominee" , koreanTitle: "" },
  { year: "1966", chineseTitle: "夏威夷", englishTitle: "Hawaii", cinematographer: "Russell Harlan", award: "Nominee" , koreanTitle: "" },
  { year: "1966", chineseTitle: "职业大贼", englishTitle: "The Professionals", cinematographer: "Conrad Hall", award: "Nominee" , koreanTitle: "" },
  { year: "1966", chineseTitle: "沙砾魔术师", englishTitle: "The Sand Pebbles", cinematographer: "Joseph MacDonald", award: "Nominee" , koreanTitle: "" },
  { year: "1965", chineseTitle: "傻瓜之船", englishTitle: "Ship of Fools", cinematographer: "Ernest Laszlo", award: "Winner" , koreanTitle: "" },
  { year: "1965", chineseTitle: "处于危险之中", englishTitle: "In Harm's Way", cinematographer: "Loyal Griggs", award: "Nominee" , koreanTitle: "" },
  { year: "1965", chineseTitle: "鼠王", englishTitle: "King Rat", cinematographer: "Burnett Guffey", award: "Nominee" , koreanTitle: "" },
  { year: "1965", chineseTitle: "中条山", englishTitle: "Morituri", cinematographer: "Conrad Hall", award: "Nominee" , koreanTitle: "" },
  { year: "1965", chineseTitle: "一块蓝色的小片地", englishTitle: "A Patch of Blue", cinematographer: "Robert Burks", award: "Nominee" , koreanTitle: "" },
  { year: "1965", chineseTitle: "日瓦戈医生", englishTitle: "Doctor Zhivago", cinematographer: "Freddie Young", award: "Winner" , koreanTitle: "" },
  { year: "1965", chineseTitle: "苦难与狂喜", englishTitle: "The Agony and the Ecstasy", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1965", chineseTitle: "伟大的竞赛", englishTitle: "The Great Race", cinematographer: "Russell Harlan", award: "Nominee" , koreanTitle: "" },
  { year: "1965", chineseTitle: "万世流芳", englishTitle: "The Greatest Story Ever Told", cinematographer: "William C. Mellor and Loyal Griggs", award: "Nominee" , koreanTitle: "" },
  { year: "1965", chineseTitle: "音乐之声", englishTitle: "The Sound of Music", cinematographer: "Ted D. McCord", award: "Nominee" , koreanTitle: "" },
  { year: "1964", chineseTitle: "希腊的佐尔巴", englishTitle: "Zorba the Greek", cinematographer: "Walter Lassally", award: "Winner" , koreanTitle: "" },
  { year: "1964", chineseTitle: "爱玛莉的美国化", englishTitle: "The Americanization of Emily", cinematographer: "Philip H. Lathrop", award: "Nominee" , koreanTitle: "" },
  { year: "1964", chineseTitle: "命运就是猎人", englishTitle: "Fate Is the Hunter", cinematographer: "Milton Krasner", award: "Nominee" , koreanTitle: "" },
  { year: "1964", chineseTitle: "最毒妇人心", englishTitle: "Hush...Hush, Sweet Charlotte", cinematographer: "Joseph Biroc", award: "Nominee" , koreanTitle: "" },
  { year: "1964", chineseTitle: "鬣蜥的夜晚", englishTitle: "The Night of the Iguana", cinematographer: "Gabriel Figueroa", award: "Nominee" , koreanTitle: "" },
  { year: "1964", chineseTitle: "我的贵妇人", englishTitle: "My Fair Lady", cinematographer: "Harry Stradling", award: "Winner" , koreanTitle: "" },
  { year: "1964", chineseTitle: "贝克特", englishTitle: "Becket", cinematographer: "Geoffrey Unsworth", award: "Nominee" , koreanTitle: "" },
  { year: "1964", chineseTitle: "产自雪山镇", englishTitle: "Cheyenne Autumn", cinematographer: "William H. Clothier", award: "Nominee" , koreanTitle: "" },
  { year: "1964", chineseTitle: "玛丽·波普斯", englishTitle: "Mary Poppins", cinematographer: "Edward Colman", award: "Nominee" , koreanTitle: "" },
  { year: "1964", chineseTitle: "不可沉没的莫莉·布朗", englishTitle: "The Unsinkable Molly Brown", cinematographer: "Daniel L. Fapp", award: "Nominee" , koreanTitle: "" },
  { year: "1963", chineseTitle: "哈德", englishTitle: "Hud", cinematographer: "James Wong Howe", award: "Winner" , koreanTitle: "" },
  { year: "1963", chineseTitle: "露台", englishTitle: "The Balcony", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1963", chineseTitle: "照顾者", englishTitle: "The Caretakers", cinematographer: "Lucien Ballard", award: "Nominee" , koreanTitle: "" },
  { year: "1963", chineseTitle: "田野里的百合花", englishTitle: "Lilies of the Field", cinematographer: "Ernest Haller", award: "Nominee" , koreanTitle: "" },
  { year: "1963", chineseTitle: "陌生人之恋", englishTitle: "Love with the Proper Stranger", cinematographer: "Milton Krasner", award: "Nominee" , koreanTitle: "" },
  { year: "1963", chineseTitle: "克莉奥佩特拉", englishTitle: "Cleopatra", cinematographer: "Leon Shamroy", award: "Winner" , koreanTitle: "" },
  { year: "1963", chineseTitle: "红衣主教", englishTitle: "The Cardinal", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1963", chineseTitle: "西部大冒险", englishTitle: "How the West Was Won", cinematographer: "William Daniels, Milton Krasner, Charles Lang and Joseph LaShelle", award: "Nominee" , koreanTitle: "" },
  { year: "1963", chineseTitle: "爱玛之女", englishTitle: "Irma la Douce", cinematographer: "Joseph LaShelle", award: "Nominee" , koreanTitle: "" },
  { year: "1963", chineseTitle: "癫狂、癫狂、癫狂的世界", englishTitle: "It's a Mad, Mad, Mad, Mad World", cinematographer: "Ernest Laszlo", award: "Nominee" , koreanTitle: "" },
  { year: "1962", chineseTitle: "最长的一天", englishTitle: "The Longest Day", cinematographer: "Jean Bourgoin and Walter Wottitz", award: "Winner" , koreanTitle: "" },
  { year: "1962", chineseTitle: "阿尔卡特拉兹的鸟人", englishTitle: "Birdman of Alcatraz", cinematographer: "Burnett Guffey", award: "Nominee" , koreanTitle: "" },
  { year: "1962", chineseTitle: "杀死一只知更鸟", englishTitle: "To Kill a Mockingbird", cinematographer: "Russell Harlan", award: "Nominee" , koreanTitle: "" },
  { year: "1962", chineseTitle: "摇摆的两个人", englishTitle: "Two for the Seesaw", cinematographer: "Ted D. McCord", award: "Nominee" , koreanTitle: "" },
  { year: "1962", chineseTitle: "珍妮小姐到底发生了什么？", englishTitle: "What Ever Happened to Baby Jane?", cinematographer: "Ernest Haller", award: "Nominee" , koreanTitle: "" },
  { year: "1962", chineseTitle: "阿拉伯的劳伦斯", englishTitle: "Lawrence of Arabia", cinematographer: "Freddie Young", award: "Winner" , koreanTitle: "" },
  { year: "1962", chineseTitle: "歌女", englishTitle: "Gypsy", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1962", chineseTitle: "哈塔里！", englishTitle: "Hatari!", cinematographer: "Russell Harlan", award: "Nominee" , koreanTitle: "" },
  { year: "1962", chineseTitle: "赏金船的叛变", englishTitle: "Mutiny on the Bounty", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1962", chineseTitle: "格林兄弟的奇妙世界", englishTitle: "The Wonderful World of the Brothers Grimm", cinematographer: "Paul C. Vogel", award: "Nominee" , koreanTitle: "" },
  { year: "1961", chineseTitle: "撬跳者", englishTitle: "The Hustler", cinematographer: "Eugen Schüfftan", award: "Winner" , koreanTitle: "" },
  { year: "1961", chineseTitle: "MindedProfessor", englishTitle: "The Absent-Minded Professor", cinematographer: "Edward Colman", award: "Nominee" , koreanTitle: "" },
  { year: "1961", chineseTitle: "孩子们的钟点", englishTitle: "The Children's Hour", cinematographer: "Franz Planer", award: "Nominee" , koreanTitle: "" },
  { year: "1961", chineseTitle: "在纽伦堡的审判", englishTitle: "Judgment at Nuremberg", cinematographer: "Ernest Laszlo", award: "Nominee" , koreanTitle: "" },
  { year: "1961", chineseTitle: "一、二、三", englishTitle: "One, Two, Three", cinematographer: "Daniel L. Fapp", award: "Nominee" , koreanTitle: "" },
  { year: "1961", chineseTitle: "西区故事", englishTitle: "West Side Story", cinematographer: "Daniel L. Fapp", award: "Winner" , koreanTitle: "웨스트 사이드 스토리" },
  { year: "1961", chineseTitle: "法妮", englishTitle: "Fanny", cinematographer: "Jack Cardiff", award: "Nominee" , koreanTitle: "" },
  { year: "1961", chineseTitle: "花鼓歌", englishTitle: "Flower Drum Song", cinematographer: "Russell Metty", award: "Nominee" , koreanTitle: "" },
  { year: "1961", chineseTitle: "以一投多", englishTitle: "A Majority of One", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1961", chineseTitle: "EyedJacks", englishTitle: "One-Eyed Jacks", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1960", chineseTitle: "儿子与情人", englishTitle: "Sons and Lovers", cinematographer: "Freddie Francis", award: "Winner" , koreanTitle: "" },
  { year: "1960", chineseTitle: "公寓", englishTitle: "The Apartment", cinematographer: "Joseph LaShelle", award: "Nominee" , koreanTitle: "" },
  { year: "1960", chineseTitle: "生活的事实", englishTitle: "The Facts of Life", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1960", chineseTitle: "风中的遗产", englishTitle: "Inherit the Wind", cinematographer: "Ernest Laszlo", award: "Nominee" , koreanTitle: "" },
  { year: "1960", chineseTitle: "精神病患者", englishTitle: "Psycho", cinematographer: "John L. Russell", award: "Nominee" , koreanTitle: "" },
  { year: "1960", chineseTitle: "斯巴达克斯", englishTitle: "Spartacus", cinematographer: "Russell Metty", award: "Winner" , koreanTitle: "" },
  { year: "1960", chineseTitle: "阿拉莫", englishTitle: "The Alamo", cinematographer: "William H. Clothier", award: "Nominee" , koreanTitle: "" },
  { year: "1960", chineseTitle: "8号巴特菲尔德女士", englishTitle: "BUtterfield 8", cinematographer: "Joseph Ruttenberg and Charles Harten", award: "Nominee" , koreanTitle: "" },
  { year: "1960", chineseTitle: "出埃及记", englishTitle: "Exodus", cinematographer: "Sam Leavitt", award: "Nominee" , koreanTitle: "" },
  { year: "1960", chineseTitle: "佩佩", englishTitle: "Pepe", cinematographer: "Joseph MacDonald", award: "Nominee" , koreanTitle: "" },
  { year: "1959", chineseTitle: "安妮·弗兰克的日记", englishTitle: "The Diary of Anne Frank", cinematographer: "William C. Mellor", award: "Winner" , koreanTitle: "" },
  { year: "1959", chineseTitle: "谋杀剖析", englishTitle: "Anatomy of a Murder", cinematographer: "Sam Leavitt", award: "Nominee" , koreanTitle: "" },
  { year: "1959", chineseTitle: "职业生涯", englishTitle: "Career", cinematographer: "Joseph LaShelle", award: "Nominee" , koreanTitle: "" },
  { year: "1959", chineseTitle: "热情如初", englishTitle: "Some Like It Hot", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1959", chineseTitle: "好莱坞之声", englishTitle: "The Young Philadelphians", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1959", chineseTitle: "贝尔·赫斯", englishTitle: "Ben Hur", cinematographer: "Robert Surtees", award: "Winner" , koreanTitle: "" },
  { year: "1959", chineseTitle: "大渔夫", englishTitle: "The Big Fisherman", cinematographer: "Lee Garmes", award: "Nominee" , koreanTitle: "" },
  { year: "1959", chineseTitle: "一角五分钱", englishTitle: "The Five Pennies", cinematographer: "Daniel L. Fapp", award: "Nominee" , koreanTitle: "" },
  { year: "1959", chineseTitle: "修女的故事", englishTitle: "The Nun's Story", cinematographer: "Franz Planer", award: "Nominee" , koreanTitle: "" },
  { year: "1959", chineseTitle: "波吉与贝丝", englishTitle: "Porgy and Bess", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1958", chineseTitle: "拒不认输的人", englishTitle: "The Defiant Ones", cinematographer: "Sam Leavitt", award: "Winner" , koreanTitle: "" },
  { year: "1958", chineseTitle: "榆树下的情愫", englishTitle: "Desire Under the Elms", cinematographer: "Daniel L. Fapp", award: "Nominee" , koreanTitle: "" },
  { year: "1958", chineseTitle: "我想活下去！", englishTitle: "I Want to Live!", cinematographer: "Lionel Lindon", award: "Nominee" , koreanTitle: "" },
  { year: "1958", chineseTitle: "分开的桌子", englishTitle: "Separate Tables", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1958", chineseTitle: "年轻的狮子们", englishTitle: "The Young Lions", cinematographer: "Joseph MacDonald", award: "Nominee" , koreanTitle: "" },
  { year: "1958", chineseTitle: "吉吉", englishTitle: "Gigi", cinematographer: "Joseph Ruttenberg", award: "Winner" , koreanTitle: "" },
  { year: "1958", chineseTitle: "玛姆姨", englishTitle: "Auntie Mame", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1958", chineseTitle: "热铁皮屋顶上的猫", englishTitle: "Cat on a Hot Tin Roof", cinematographer: "William Daniels", award: "Nominee" , koreanTitle: "" },
  { year: "1958", chineseTitle: "老人与海", englishTitle: "The Old Man and the Sea", cinematographer: "James Wong Howe", award: "Nominee" , koreanTitle: "" },
  { year: "1958", chineseTitle: "南太平洋", englishTitle: "South Pacific", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1957", chineseTitle: "桥上的江湖", englishTitle: "The Bridge on the River Kwai", cinematographer: "Jack Hildyard", award: "Winner" , koreanTitle: "" },
  { year: "1957", chineseTitle: "一段难以忘记的情缘", englishTitle: "An Affair to Remember", cinematographer: "Milton Krasner", award: "Nominee" , koreanTitle: "" },
  { year: "1957", chineseTitle: "滑稽女郎", englishTitle: "Funny Face", cinematographer: "Ray June", award: "Nominee" , koreanTitle: "" },
  { year: "1957", chineseTitle: "佩顿地区", englishTitle: "Peyton Place", cinematographer: "William C. Mellor", award: "Nominee" , koreanTitle: "" },
  { year: "1957", chineseTitle: "再见", englishTitle: "Sayonara", cinematographer: "Ellsworth Fredericks", award: "Nominee" , koreanTitle: "" },
  { year: "1956", chineseTitle: "上天缘何喜欢我", englishTitle: "Somebody Up There Likes Me", cinematographer: "Joseph Ruttenberg", award: "Winner" , koreanTitle: "" },
  { year: "1956", chineseTitle: "娃娃", englishTitle: "Baby Doll", cinematographer: "Boris Kaufman", award: "Nominee" , koreanTitle: "" },
  { year: "1956", chineseTitle: "坏种子", englishTitle: "The Bad Seed", cinematographer: "Harold Rosson", award: "Nominee" , koreanTitle: "" },
  { year: "1956", chineseTitle: "跌得越狠", englishTitle: "The Harder They Fall", cinematographer: "Burnett Guffey", award: "Nominee" , koreanTitle: "" },
  { year: "1956", chineseTitle: "愤怒马车", englishTitle: "Stagecoach to Fury", cinematographer: "Walter Strenge", award: "Nominee" , koreanTitle: "" },
  { year: "1956", chineseTitle: "全球游记80天", englishTitle: "Around the World in 80 Days", cinematographer: "Lionel Lindon", award: "Winner" , koreanTitle: "" },
  { year: "1956", chineseTitle: "埃迪·杜钦的故事", englishTitle: "The Eddy Duchin Story", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1956", chineseTitle: "国王与我", englishTitle: "The King and I", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1956", chineseTitle: "十诫", englishTitle: "The Ten Commandments", cinematographer: "Loyal Griggs", award: "Nominee" , koreanTitle: "" },
  { year: "1956", chineseTitle: "战争与和平", englishTitle: "War and Peace", cinematographer: "Jack Cardiff", award: "Nominee" , koreanTitle: "" },
  { year: "1955", chineseTitle: "玫瑰刺青", englishTitle: "The Rose Tattoo", cinematographer: "James Wong Howe", award: "Winner" , koreanTitle: "" },
  { year: "1955", chineseTitle: "黑板丛林", englishTitle: "Blackboard Jungle", cinematographer: "Russell Harlan", award: "Nominee" , koreanTitle: "" },
  { year: "1955", chineseTitle: "明天我会哭泣", englishTitle: "I'll Cry Tomorrow", cinematographer: "Arthur Arling", award: "Nominee" , koreanTitle: "" },
  { year: "1955", chineseTitle: "玛蒂", englishTitle: "Marty", cinematographer: "Joseph LaShelle", award: "Nominee" , koreanTitle: "" },
  { year: "1955", chineseTitle: "女王蜂", englishTitle: "Queen Bee", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1955", chineseTitle: "抓住窃贼", englishTitle: "To Catch a Thief", cinematographer: "Robert Burks", award: "Winner" , koreanTitle: "" },
  { year: "1955", chineseTitle: "扳着手指数人头", englishTitle: "Guys and Dolls", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1955", chineseTitle: "SplendoredThing", englishTitle: "Love Is a Many-Splendored Thing", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1955", chineseTitle: "一个名叫彼得的人", englishTitle: "A Man Called Peter", cinematographer: "Harold Lipstein", award: "Nominee" , koreanTitle: "" },
  { year: "1955", chineseTitle: "俄克拉荷马", englishTitle: "Oklahoma!", cinematographer: "Robert Surtees", award: "Nominee" , koreanTitle: "" },
  { year: "1954", chineseTitle: "码头风云", englishTitle: "On the Waterfront", cinematographer: "Boris Kaufman", award: "Winner" , koreanTitle: "" },
  { year: "1954", chineseTitle: "乡村女孩", englishTitle: "The Country Girl", cinematographer: "John F. Warren", award: "Nominee" , koreanTitle: "" },
  { year: "1954", chineseTitle: "纵横天下", englishTitle: "Executive Suite", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1954", chineseTitle: "背信弃义的警察", englishTitle: "Rogue Cop", cinematographer: "John F. Seitz", award: "Nominee" , koreanTitle: "" },
  { year: "1954", chineseTitle: "萨布丽娜", englishTitle: "Sabrina", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1954", chineseTitle: "罗马之恋", englishTitle: "Three Coins in the Fountain", cinematographer: "Milton Krasner", award: "Winner" , koreanTitle: "" },
  { year: "1954", chineseTitle: "埃及人", englishTitle: "The Egyptian", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1954", chineseTitle: "后窗", englishTitle: "Rear Window", cinematographer: "Robert Burks", award: "Nominee" , koreanTitle: "" },
  { year: "1954", chineseTitle: "七个兄弟的七个新娘", englishTitle: "Seven Brides for Seven Brothers", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1954", chineseTitle: "镶银圣杯", englishTitle: "The Silver Chalice", cinematographer: "William V. Skall", award: "Nominee" , koreanTitle: "" },
  { year: "1953", chineseTitle: "从此到永远", englishTitle: "From Here to Eternity", cinematographer: "Burnett Guffey", award: "Winner" , koreanTitle: "" },
  { year: "1953", chineseTitle: "人生曲", englishTitle: "The Four Poster", cinematographer: "Hal Mohr", award: "Nominee" , koreanTitle: "" },
  { year: "1953", chineseTitle: "凯撒大帝", englishTitle: "Julius Caesar", cinematographer: "Joseph Ruttenberg", award: "Nominee" , koreanTitle: "" },
  { year: "1953", chineseTitle: "马丁·路德", englishTitle: "Martin Luther", cinematographer: "Joseph C. Brun", award: "Nominee" , koreanTitle: "" },
  { year: "1953", chineseTitle: "罗马假日", englishTitle: "Roman Holiday", cinematographer: "Franz Planer and Henri Alekan", award: "Nominee" , koreanTitle: "" },
  { year: "1953", chineseTitle: "雪恩", englishTitle: "Shane", cinematographer: "Loyal Griggs", award: "Winner" , koreanTitle: "" },
  { year: "1953", chineseTitle: "四海英雄传", englishTitle: "All the Brothers Were Valiant", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1953", chineseTitle: "MileReef", englishTitle: "Beneath the 12-Mile Reef", cinematographer: "Edward Cronjager", award: "Nominee" , koreanTitle: "" },
  { year: "1953", chineseTitle: "莉莉", englishTitle: "Lili", cinematographer: "Robert H. Planck", award: "Nominee" , koreanTitle: "" },
  { year: "1953", chineseTitle: "波旁王朝", englishTitle: "The Robe", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1952", chineseTitle: "坏与美", englishTitle: "The Bad and the Beautiful", cinematographer: "Robert Surtees", award: "Winner" , koreanTitle: "" },
  { year: "1952", chineseTitle: "峰火弥天", englishTitle: "The Big Sky", cinematographer: "Russell Harlan", award: "Nominee" , koreanTitle: "" },
  { year: "1952", chineseTitle: "我的表妹瑞秋", englishTitle: "My Cousin Rachel", cinematographer: "Joseph LaShelle", award: "Nominee" , koreanTitle: "" },
  { year: "1952", chineseTitle: "纳瓦哈", englishTitle: "Navajo", cinematographer: "Virgil Miller", award: "Nominee" , koreanTitle: "" },
  { year: "1952", chineseTitle: "骤然恐慌", englishTitle: "Sudden Fear", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1952", chineseTitle: "安静的人", englishTitle: "The Quiet Man", cinematographer: "Winton C. Hoch and Archie Stout", award: "Winner" , koreanTitle: "" },
  { year: "1952", chineseTitle: "安徒生", englishTitle: "Hans Christian Andersen", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1952", chineseTitle: "艾凡豪", englishTitle: "Ivanhoe", cinematographer: "Freddie Young", award: "Nominee" , koreanTitle: "" },
  { year: "1952", chineseTitle: "百万美人鱼", englishTitle: "Million Dollar Mermaid", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1952", chineseTitle: "基利马札罗的雪", englishTitle: "The Snows of Kilimanjaro", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1951", chineseTitle: "日落大道", englishTitle: "A Place in the Sun", cinematographer: "William C. Mellor", award: "Winner" , koreanTitle: "" },
  { year: "1951", chineseTitle: "一位推销员的死亡", englishTitle: "Death of a Salesman", cinematographer: "Franz Planer", award: "Nominee" , koreanTitle: "" },
  { year: "1951", chineseTitle: "蛙人", englishTitle: "The Frogmen", cinematographer: "Norbert Brodine", award: "Nominee" , koreanTitle: "" },
  { year: "1951", chineseTitle: "列车上的陌生人", englishTitle: "Strangers on a Train", cinematographer: "Robert Burks", award: "Nominee" , koreanTitle: "" },
  { year: "1951", chineseTitle: "欲望号街车", englishTitle: "A Streetcar Named Desire", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1951", chineseTitle: "天空之城", englishTitle: "An American in Paris", cinematographer: "Alfred Gilks and John Alton", award: "Winner" , koreanTitle: "" },
  { year: "1951", chineseTitle: "大卫与拔示巴", englishTitle: "David and Bathsheba", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1951", chineseTitle: "全世界和平", englishTitle: "Quo Vadis", cinematographer: "Robert Surtees and William V. Skall", award: "Nominee" , koreanTitle: "" },
  { year: "1951", chineseTitle: "船歌", englishTitle: "Show Boat", cinematographer: "Charles Rosher", award: "Nominee" , koreanTitle: "" },
  { year: "1951", chineseTitle: "当世界碰撞时", englishTitle: "When Worlds Collide", cinematographer: "John F. Seitz and W. Howard Greene", award: "Nominee" , koreanTitle: "" },
  { year: "1950", chineseTitle: "第三个男人", englishTitle: "The Third Man", cinematographer: "Robert Krasker", award: "Winner" , koreanTitle: "" },
  { year: "1950", chineseTitle: "伊芙女士", englishTitle: "All About Eve", cinematographer: "Milton Krasner", award: "Nominee" , koreanTitle: "" },
  { year: "1950", chineseTitle: "沥青丛林", englishTitle: "The Asphalt Jungle", cinematographer: "Harold Rosson", award: "Nominee" , koreanTitle: "" },
  { year: "1950", chineseTitle: "势不两立", englishTitle: "The Furies", cinematographer: "Victor Milner", award: "Nominee" , koreanTitle: "" },
  { year: "1950", chineseTitle: "天堂大道", englishTitle: "Sunset Boulevard", cinematographer: "John F. Seitz", award: "Nominee" , koreanTitle: "" },
  { year: "1950", chineseTitle: "所罗门王宝藏", englishTitle: "King Solomon's Mines", cinematographer: "Robert Surtees", award: "Winner" , koreanTitle: "" },
  { year: "1950", chineseTitle: "安妮带上你的枪", englishTitle: "Annie Get Your Gun", cinematographer: "Charles Rosher", award: "Nominee" , koreanTitle: "" },
  { year: "1950", chineseTitle: "断箭", englishTitle: "Broken Arrow", cinematographer: "Ernest Palmer", award: "Nominee" , koreanTitle: "" },
  { year: "1950", chineseTitle: "火焰与箭", englishTitle: "The Flame and the Arrow", cinematographer: "Ernest Haller", award: "Nominee" , koreanTitle: "" },
  { year: "1950", chineseTitle: "参孙和达莉拉", englishTitle: "Samson and Delilah", cinematographer: "George Barnes", award: "Nominee" , koreanTitle: "" },
  { year: "1949", chineseTitle: "阵地战", englishTitle: "Battleground", cinematographer: "Paul C. Vogel", award: "Winner" , koreanTitle: "" },
  { year: "1949", chineseTitle: "冠军", englishTitle: "Champion", cinematographer: "Franz Planer", award: "Nominee" , koreanTitle: "" },
  { year: "1949", chineseTitle: "来马厩", englishTitle: "Come to the Stable", cinematographer: "Joseph LaShelle", award: "Nominee" , koreanTitle: "" },
  { year: "1949", chineseTitle: "继承人", englishTitle: "The Heiress", cinematographer: "Leo Tover", award: "Nominee" , koreanTitle: "" },
  { year: "1949", chineseTitle: "狐狸王子", englishTitle: "Prince of Foxes", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1949", chineseTitle: "她佩戴着一条黄丝带", englishTitle: "She Wore a Yellow Ribbon", cinematographer: "Winton C. Hoch", award: "Winner" , koreanTitle: "" },
  { year: "1949", chineseTitle: "街头巴克利", englishTitle: "The Barkleys of Broadway", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1949", chineseTitle: "乔尔森再度献声", englishTitle: "Jolson Sings Again", cinematographer: "William E. Snyder", award: "Nominee" , koreanTitle: "" },
  { year: "1949", chineseTitle: "小妇人", englishTitle: "Little Women", cinematographer: "Robert H. Planck and Charles Schoenbaum", award: "Nominee" , koreanTitle: "" },
  { year: "1949", chineseTitle: "沙丘", englishTitle: "Sand", cinematographer: "Charles G. Clarke", award: "Nominee" , koreanTitle: "" },
  { year: "1948", chineseTitle: "裸体城市", englishTitle: "The Naked City", cinematographer: "William Daniels", award: "Winner" , koreanTitle: "" },
  { year: "1948", chineseTitle: "外事关系", englishTitle: "A Foreign Affair", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1948", chineseTitle: "慈母泪", englishTitle: "I Remember Mama", cinematographer: "Nicholas Musuraca", award: "Nominee" , koreanTitle: "" },
  { year: "1948", chineseTitle: "约翰尼·贝林达", englishTitle: "Johnny Belinda", cinematographer: "Ted D. McCord", award: "Nominee" , koreanTitle: "" },
  { year: "1948", chineseTitle: "珍妮画像", englishTitle: "Portrait of Jennie", cinematographer: "Joseph August (posthumously)", award: "Nominee" , koreanTitle: "" },
  { year: "1948", chineseTitle: "圣女贞德", englishTitle: "Joan of Arc", cinematographer: "Joseph Valentine, William V. Skall and Winton C. Hoch", award: "Winner" , koreanTitle: "" },
  { year: "1948", chineseTitle: "怀俄明的绿草原", englishTitle: "Green Grass of Wyoming", cinematographer: "Charles G. Clarke", award: "Nominee" , koreanTitle: "" },
  { year: "1948", chineseTitle: "卡门之恋", englishTitle: "The Loves of Carmen", cinematographer: "William E. Snyder", award: "Nominee" , koreanTitle: "" },
  { year: "1948", chineseTitle: "三个火枪手", englishTitle: "The Three Musketeers", cinematographer: "Robert H. Planck", award: "Nominee" , koreanTitle: "" },
  { year: "1947", chineseTitle: "伟大的期望", englishTitle: "Great Expectations", cinematographer: "Guy Green", award: "Winner" , koreanTitle: "" },
  { year: "1947", chineseTitle: "绿色海豚街", englishTitle: "Green Dolphin Street", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1947", chineseTitle: "幽灵与穆尔夫人", englishTitle: "The Ghost and Mrs. Muir", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1947", chineseTitle: "黑色那无华", englishTitle: "Black Narcissus", cinematographer: "Jack Cardiff", award: "Winner" , koreanTitle: "" },
  { year: "1947", chineseTitle: "父亲的生活", englishTitle: "Life with Father", cinematographer: "J. Peverell Marley and William V. Skall", award: "Nominee" , koreanTitle: "" },
  { year: "1947", chineseTitle: "金缕霓裳", englishTitle: "Mother Wore Tights", cinematographer: "Harry Jackson", award: "Nominee" , koreanTitle: "" },
  { year: "1946", chineseTitle: "安娜和暹罗国王", englishTitle: "Anna and the King of Siam", cinematographer: "Arthur C. Miller", award: "Winner" , koreanTitle: "" },
  { year: "1946", chineseTitle: "绿色年华", englishTitle: "The Green Years", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1946", chineseTitle: "小鹿斑比", englishTitle: "The Yearling", cinematographer: "Charles Rosher, Leonard Smith and Arthur Arling", award: "Winner" , koreanTitle: "" },
  { year: "1946", chineseTitle: "乔尔森的故事", englishTitle: "The Jolson Story", cinematographer: "Joseph Walker", award: "Nominee" , koreanTitle: "" },
  { year: "1945", chineseTitle: "多里安·格雷的画像", englishTitle: "The Picture of Dorian Gray", cinematographer: "Harry Stradling", award: "Winner" , koreanTitle: "" },
  { year: "1945", chineseTitle: "身份的钥匙", englishTitle: "The Keys of the Kingdom", cinematographer: "Arthur C. Miller", award: "Nominee" , koreanTitle: "" },
  { year: "1945", chineseTitle: "失落的周末", englishTitle: "The Lost Weekend", cinematographer: "John F. Seitz", award: "Nominee" , koreanTitle: "" },
  { year: "1945", chineseTitle: "米尔得瓦德·皮尔斯", englishTitle: "Mildred Pierce", cinematographer: "Ernest Haller", award: "Nominee" , koreanTitle: "" },
  { year: "1945", chineseTitle: "催眠", englishTitle: "Spellbound", cinematographer: "George Barnes", award: "Nominee" , koreanTitle: "" },
  { year: "1945", chineseTitle: "将她留在天堂", englishTitle: "Leave Her to Heaven", cinematographer: "Leon Shamroy", award: "Winner" , koreanTitle: "" },
  { year: "1945", chineseTitle: "锚扬帆", englishTitle: "Anchors Aweigh", cinematographer: "Robert H. Planck and Charles P. Boyle", award: "Nominee" , koreanTitle: "" },
  { year: "1945", chineseTitle: "国家天鹅绒", englishTitle: "National Velvet", cinematographer: "Leonard Smith", award: "Nominee" , koreanTitle: "" },
  { year: "1945", chineseTitle: "记忆之歌", englishTitle: "A Song to Remember", cinematographer: "Tony Gaudio and Allen M. Davey", award: "Nominee" , koreanTitle: "" },
  { year: "1945", chineseTitle: "百慕大怪船", englishTitle: "The Spanish Main", cinematographer: "George Barnes", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "老娘鱼", englishTitle: "Laura", cinematographer: "Joseph LaShelle", award: "Winner" , koreanTitle: "" },
  { year: "1944", chineseTitle: "双重赔偿", englishTitle: "Double Indemnity", cinematographer: "John F. Seitz", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "龙种", englishTitle: "Dragon Seed", cinematographer: "Sidney Wagner", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "煤气灯", englishTitle: "Gaslight", cinematographer: "Joseph Ruttenberg", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "向前走", englishTitle: "Going My Way", cinematographer: "Lionel Lindon", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "救生艇", englishTitle: "Lifeboat", cinematographer: "Glen MacWilliams", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "你离开后", englishTitle: "Since You Went Away", cinematographer: "Stanley Cortez and Lee Garmes", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "三十秒飞越东京", englishTitle: "Thirty Seconds Over Tokyo", cinematographer: "Robert Surtees and Harold Rosson", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "未被邀请的人", englishTitle: "The Uninvited", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "多佛尔的白崖", englishTitle: "The White Cliffs of Dover", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "威尔逊", englishTitle: "Wilson", cinematographer: "Leon Shamroy", award: "Winner" , koreanTitle: "" },
  { year: "1944", chineseTitle: "封面女郎", englishTitle: "Cover Girl", cinematographer: "Rudolph Maté and Allen M. Davey", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "印地安纳之家", englishTitle: "Home in Indiana", cinematographer: "Edward Cronjager", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "命运之奇迹", englishTitle: "Kismet", cinematographer: "Charles Rosher", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "黑暗中的女士", englishTitle: "Lady in the Dark", cinematographer: "Ray Rennahan", award: "Nominee" , koreanTitle: "" },
  { year: "1944", chineseTitle: "在圣路易斯见我", englishTitle: "Meet Me in St. Louis", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "波南度的歌声", englishTitle: "The Song of Bernadette", cinematographer: "Arthur C. Miller", award: "Winner" , koreanTitle: "" },
  { year: "1943", chineseTitle: "空军", englishTitle: "Air Force", cinematographer: "James Wong Howe, Elmer Dyer and Charles A. Marshall", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "卡萨布兰卡", englishTitle: "Casablanca", cinematographer: "Arthur Edeson", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "大西洋之战", englishTitle: "Corvette K-225", cinematographer: "Tony Gaudio", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "开罗的五个坟墓", englishTitle: "Five Graves to Cairo", cinematographer: "John F. Seitz", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "人间喜剧", englishTitle: "The Human Comedy", cinematographer: "Harry Stradling", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "居里夫人", englishTitle: "Madame Curie", cinematographer: "Joseph Ruttenberg", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "北极星", englishTitle: "The North Star", cinematographer: "James Wong Howe", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "撒哈拉", englishTitle: "Sahara", cinematographer: "Rudolph Maté", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "我们雄辩地歌颂！", englishTitle: "So Proudly We Hail!", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "歌剧魅影", englishTitle: "Phantom of the Opera", cinematographer: "Hal Mohr and W. Howard Greene", award: "Winner" , koreanTitle: "" },
  { year: "1943", chineseTitle: "丧钟为谁而鸣", englishTitle: "For Whom the Bell Tolls", cinematographer: "Ray Rennahan", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "天堂可以等待", englishTitle: "Heaven Can Wait", cinematographer: "Edward Cronjager", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "春风得意", englishTitle: "Hello Frisco, Hello", cinematographer: "Charles G. Clarke and Allen M. Davey", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "来吧，莱西", englishTitle: "Lassie Come Home", cinematographer: "Leonard Smith", award: "Nominee" , koreanTitle: "" },
  { year: "1943", chineseTitle: "千万欢呼", englishTitle: "Thousands Cheer", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "米尼弗夫人", englishTitle: "Mrs. Miniver", cinematographer: "Joseph Ruttenberg", award: "Winner" , koreanTitle: "" },
  { year: "1942", chineseTitle: "国王纪元", englishTitle: "Kings Row", cinematographer: "James Wong Howe", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "安伯森一家的华丽", englishTitle: "The Magnificent Ambersons", cinematographer: "Stanley Cortez", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "潮水", englishTitle: "Moontide", cinematographer: "Charles G. Clarke", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "排笛手", englishTitle: "The Pied Piper", cinematographer: "Edward Cronjager", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "美国人民的骄傲", englishTitle: "The Pride of the Yankees", cinematographer: "Rudolph Maté", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "亲爱的，写一封信", englishTitle: "Take a Letter, Darling", cinematographer: "John J. Mescall", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "小镇传闻", englishTitle: "The Talk of the Town", cinematographer: "Ted Tetzlaff", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "十位来自西点的绅士", englishTitle: "Ten Gentlemen from West Point", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "除此以外的", englishTitle: "This Above All", cinematographer: "Arthur C. Miller", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "黑天鹅", englishTitle: "The Black Swan", cinematographer: "Leon Shamroy", award: "Winner" , koreanTitle: "" },
  { year: "1942", chineseTitle: "阿拉伯之夜", englishTitle: "Arabian Nights", cinematographer: "Milton Krasner, William V. Skall and W. Howard Greene", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "云的船长", englishTitle: "Captains of the Clouds", cinematographer: "Sol Polito", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "丛林书", englishTitle: "Jungle Book", cinematographer: "W. Howard Greene", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "收割狂风", englishTitle: "Reap the Wild Wind", cinematographer: "Victor Milner and William V. Skall", award: "Nominee" , koreanTitle: "" },
  { year: "1942", chineseTitle: "到的黎波里海岸", englishTitle: "To the Shores of Tripoli", cinematographer: "Edward Cronjager and William V. Skall", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "我的青草地", englishTitle: "How Green Was My Valley", cinematographer: "Arthur C. Miller", award: "Winner" , koreanTitle: "" },
  { year: "1941", chineseTitle: "巧克力士兵", englishTitle: "The Chocolate Soldier", cinematographer: "Karl Freund", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "公民凯恩", englishTitle: "Citizen Kane", cinematographer: "Gregg Toland", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "杰克尔与海德博士", englishTitle: "Dr. Jekyll and Mr. Hyde", cinematographer: "Joseph Ruttenberg", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "乔丹来了", englishTitle: "Here Comes Mr. Jordan", cinematographer: "Joseph Walker", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "忍耐黎明", englishTitle: "Hold Back the Dawn", cinematographer: "Leo Tover", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "约克军士", englishTitle: "Sergeant York", cinematographer: "Sol Polito", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "日落山谷的狂想曲", englishTitle: "Sun Valley Serenade", cinematographer: "Edward Cronjager", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "日落时分", englishTitle: "Sundown", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "汉密尔顿女士", englishTitle: "That Hamilton Woman", cinematographer: "Rudolph Maté", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "血与沙", englishTitle: "Blood and Sand", cinematographer: "Ernest Palmer and Ray Rennahan", award: "Winner" , koreanTitle: "" },
  { year: "1941", chineseTitle: "南海的阿洛玛", englishTitle: "Aloma of the South Seas", cinematographer: "Wilfred M. Cline, Karl Struss and William E. Snyder", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "埃尔", englishTitle: "Billy the Kid", cinematographer: "William V. Skall and Leonard Smith", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "土中开花", englishTitle: "Blossoms in the Dust", cinematographer: "Karl Freund and W. Howard Greene", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "俯冲轰炸机", englishTitle: "Dive Bomber", cinematographer: "Bert Glennon", award: "Nominee" , koreanTitle: "" },
  { year: "1941", chineseTitle: "路易斯安那购买", englishTitle: "Louisiana Purchase", cinematographer: "Harry Hallenberger and Ray Rennahan", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "惹卡迷", englishTitle: "Rebecca", cinematographer: "George Barnes", award: "Winner" , koreanTitle: "" },
  { year: "1940", chineseTitle: "伊利诺斯州的林肯", englishTitle: "Abe Lincoln in Illinois", cinematographer: "James Wong Howe", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "这一切，还有天堂", englishTitle: "All This, and Heaven Too", cinematographer: "Ernest Haller", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "爱的崛起", englishTitle: "Arise, My Love", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "繁荣城市", englishTitle: "Boom Town", cinematographer: "Harold Rosson", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "外地亲事", englishTitle: "Foreign Correspondent", cinematographer: "Rudolph Maté", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "信件", englishTitle: "The Letter", cinematographer: "Tony Gaudio", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "漫长的归途", englishTitle: "The Long Voyage Home", cinematographer: "Gregg Toland", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "春天游行", englishTitle: "Spring Parade", cinematographer: "Joseph Valentine", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "滑铁卢桥", englishTitle: "Waterloo Bridge", cinematographer: "Joseph Ruttenberg", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "巴格达的盗贼", englishTitle: "The Thief of Bagdad", cinematographer: "Georges Périnal", award: "Winner" , koreanTitle: "" },
  { year: "1940", chineseTitle: "苦甜之间", englishTitle: "Bitter Sweet", cinematographer: "Oliver T. Marsh and Allen M. Davey", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "蓝鸟", englishTitle: "The Blue Bird", cinematographer: "Arthur C. Miller and Ray Rennahan", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "阿根廷之路", englishTitle: "Down Argentine Way", cinematographer: "Leon Shamroy and Ray Rennahan", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "加拿大西北驻军", englishTitle: "North West Mounted Police", cinematographer: "Victor Milner and W. Howard Greene", award: "Nominee" , koreanTitle: "" },
  { year: "1940", chineseTitle: "西北通道", englishTitle: "Northwest Passage", cinematographer: "Sidney Wagner and William V. Skall", award: "Nominee" , koreanTitle: "" },
  { year: "1939", chineseTitle: "咆哮山庄", englishTitle: "Wuthering Heights", cinematographer: "Gregg Toland", award: "Winner" , koreanTitle: "" },
  { year: "1939", chineseTitle: "马车", englishTitle: "Stagecoach", cinematographer: "Bert Glennon", award: "Nominee" , koreanTitle: "" },
  { year: "1939", chineseTitle: "乱世佳人", englishTitle: "Gone With the Wind", cinematographer: "Ernest Haller and Ray Rennahan", award: "Winner" , koreanTitle: "" },
  { year: "1939", chineseTitle: "伊丽莎白和埃塞克斯的私生活", englishTitle: "The Private Lives of Elizabeth and Essex", cinematographer: "Sol Polito and W. Howard Greene", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "伟大的华尔兹", englishTitle: "The Great Waltz", cinematographer: "Joseph Ruttenberg", award: "Winner" , koreanTitle: "" },
  { year: "1938", chineseTitle: "阿尔及尔", englishTitle: "Algiers", cinematographer: "James Wong Howe", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "军嫂", englishTitle: "Army Girl", cinematographer: "Ernest Miller and Harry J. Wild", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "海盗", englishTitle: "The Buccaneer", cinematographer: "Victor Milner", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "耶洗别", englishTitle: "Jezebel", cinematographer: "Ernest Haller", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "疯狂于音乐", englishTitle: "Mad About Music", cinematographer: "Joseph Valentine", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "生活得愉快", englishTitle: "Merrily We Live", cinematographer: "Norbert Brodine", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "苏伊士", englishTitle: "Suez", cinematographer: "J. Peverell Marley", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "活泼的女士", englishTitle: "Vivacious Lady", cinematographer: "Robert De Grasse", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "你不能带走它", englishTitle: "You Can't Take It with You", cinematographer: "Joseph Walker", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "年轻中的心灵", englishTitle: "The Young in Heart", cinematographer: "Leon Shamroy", award: "Nominee" , koreanTitle: "" },
  { year: "1938", chineseTitle: "甜心", englishTitle: "Sweethearts", cinematographer: "Oliver T. Marsh and Allen Davey", award: "Nominee" , koreanTitle: "" },
  { year: "1937", chineseTitle: "大地", englishTitle: "The Good Earth", cinematographer: "Karl Freund", award: "Winner" , koreanTitle: "" },
  { year: "1937", chineseTitle: "死胡同", englishTitle: "Dead End", cinematographer: "Gregg Toland", award: "Nominee" , koreanTitle: "" },
  { year: "1937", chineseTitle: "逍遥法外", englishTitle: "Wings over Honolulu", cinematographer: "Joseph Valentine", award: "Nominee" , koreanTitle: "" },
  { year: "1937", chineseTitle: "一颗明星的诞生", englishTitle: "A Star Is Born", cinematographer: "W. Howard Greene", award: "Nominee" , koreanTitle: "스타 이즈 본" },
  { year: "1936", chineseTitle: "安东尼·阿德斯", englishTitle: "Anthony Adverse", cinematographer: "Tony Gaudio", award: "Winner" , koreanTitle: "" },
  { year: "1936", chineseTitle: "将军在黎明时逝世", englishTitle: "The General Died at Dawn", cinematographer: "Victor Milner", award: "Nominee" , koreanTitle: "" },
  { year: "1936", chineseTitle: "美丽的贞女", englishTitle: "The Gorgeous Hussy", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1936", chineseTitle: "阿拉的花园", englishTitle: "The Garden of Allah", cinematographer: "W. Howard Greene and Harold Rosson", award: "Nominee" , koreanTitle: "" },
  { year: "1935", chineseTitle: "仲夏夜之梦", englishTitle: "A Midsummer Night's Dream", cinematographer: "Hal Mohr", award: "Winner" , koreanTitle: "" },
  { year: "1935", chineseTitle: "巴巴利海岸", englishTitle: "Barbary Coast", cinematographer: "Ray June", award: "Nominee" , koreanTitle: "" },
  { year: "1935", chineseTitle: "十字军东征", englishTitle: "The Crusades", cinematographer: "Victor Milner", award: "Nominee" , koreanTitle: "" },
  { year: "1935", chineseTitle: "悲惨世界", englishTitle: "Les Misérables", cinematographer: "Gregg Toland", award: "Nominee" , koreanTitle: "" },
  { year: "1934", chineseTitle: "克莉奥佩特拉", englishTitle: "Cleopatra", cinematographer: "Victor Milner", award: "Winner" , koreanTitle: "" },
  { year: "1934", chineseTitle: "塞利尼的恋情", englishTitle: "The Affairs of Cellini", cinematographer: "Charles Rosher", award: "Nominee" , koreanTitle: "" },
  { year: "1934", chineseTitle: "第13号操作员", englishTitle: "Operator 13", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1932/33", chineseTitle: "道别的武器", englishTitle: "A Farewell to Arms", cinematographer: "Charles Lang", award: "Winner" , koreanTitle: "" },
  { year: "1932/33", chineseTitle: "维也纳重逢", englishTitle: "Reunion in Vienna", cinematographer: "George J. Folsey", award: "Nominee" , koreanTitle: "" },
  { year: "1932/33", chineseTitle: "十字架的标志", englishTitle: "The Sign of the Cross", cinematographer: "Karl Struss", award: "Nominee" , koreanTitle: "" },
  { year: "1931/32", chineseTitle: "上海特快", englishTitle: "Shanghai Express", cinematographer: "Lee Garmes", award: "Winner" , koreanTitle: "" },
  { year: "1931/32", chineseTitle: "射手", englishTitle: "Arrowsmith", cinematographer: "Ray June", award: "Nominee" , koreanTitle: "" },
  { year: "1931/32", chineseTitle: "杰克尔博士和海德先生", englishTitle: "Dr. Jekyll and Mr. Hyde", cinematographer: "Karl Struss", award: "Nominee" , koreanTitle: "" },
  { year: "1930/31", chineseTitle: "南海的禁忌：一个故事", englishTitle: "Tabu: A Story of the South Seas", cinematographer: "Floyd Crosby", award: "Winner" , koreanTitle: "" },
  { year: "1930/31", chineseTitle: "西马隆", englishTitle: "Cimarron", cinematographer: "Edward Cronjager", award: "Nominee" , koreanTitle: "" },
  { year: "1930/31", chineseTitle: "摩洛哥", englishTitle: "Morocco", cinematographer: "Lee Garmes", award: "Nominee" , koreanTitle: "" },
  { year: "1930/31", chineseTitle: "爱的权利", englishTitle: "The Right to Love", cinematographer: "Charles Lang", award: "Nominee" , koreanTitle: "" },
  { year: "1930/31", chineseTitle: "斯文加利", englishTitle: "Svengali", cinematographer: "Barney McGill", award: "Nominee" , koreanTitle: "" },
  { year: "1929/30", chineseTitle: "与伯德一起在南极", englishTitle: "With Byrd at the South Pole", cinematographer: "Joseph T. Rucker and Willard Van der Veer", award: "Winner" , koreanTitle: "" },
  { year: "1929/30", chineseTitle: "西线无战事", englishTitle: "All Quiet on the Western Front", cinematographer: "Arthur Edeson", award: "Nominee" , koreanTitle: "서부 전선 이상 없다" },
  { year: "1929/30", chineseTitle: "安娜•克里斯蒂", englishTitle: "Anna Christie", cinematographer: "William H. Daniels", award: "Nominee" , koreanTitle: "" },
  { year: "1929/30", chineseTitle: "地狱天使", englishTitle: "Hell's Angels", cinematographer: "Tony Gaudio and Harry Perry", award: "Nominee" , koreanTitle: "" },
  { year: "1929/30", chineseTitle: "爱的巡游", englishTitle: "The Love Parade", cinematographer: "Victor Milner", award: "Nominee" , koreanTitle: "" },
  { year: "1928/29", chineseTitle: "南海的白影", englishTitle: "White Shadows in the South Seas", cinematographer: "Clyde De Vinna", award: "Winner" , koreanTitle: "" },
  { year: "1928/29", chineseTitle: "神圣的女士", englishTitle: "The Divine Lady", cinematographer: "John F. Seitz", award: "Nominee" , koreanTitle: "" },
  { year: "1928/29", chineseTitle: "四个恶魔", englishTitle: "4 Devils", cinematographer: "Ernest Palmer", award: "Nominee" , koreanTitle: "" },
  { year: "1928/29", chineseTitle: "在老亚利桑那", englishTitle: "In Old Arizona", cinematographer: "Arthur Edeson", award: "Nominee" , koreanTitle: "" },
  { year: "1928/29", chineseTitle: "我们的舞蹈女儿", englishTitle: "Our Dancing Daughters", cinematographer: "George Barnes", award: "Nominee" , koreanTitle: "" },
  { year: "1928/29", chineseTitle: "街天使", englishTitle: "Street Angel", cinematographer: "Ernest Palmer", award: "Nominee" , koreanTitle: "" },
  { year: "1927/28", chineseTitle: "日出：两个人的歌曲", englishTitle: "Sunrise: A Song of Two Humans", cinematographer: "Charles Rosher Karl Struss", award: "Winner" , koreanTitle: "" },
  { year: "1927/28", chineseTitle: "恶魔舞者", englishTitle: "The Devil Dancer", cinematographer: "George Barnes", award: "Nominee" , koreanTitle: "" },
  { year: "1927/28", chineseTitle: "神奇的火焰", englishTitle: "The Magic Flame", cinematographer: "George Barnes", award: "Nominee" , koreanTitle: "" },
  { year: "1927/28", chineseTitle: "莎迪·汤普森", englishTitle: "Sadie Thompson", cinematographer: "George Barnes", award: "Nominee" , koreanTitle: "" },
];
